export function tutorialHTML(){return `<div class="tutorial"><div class="panel"><div class="panel-head"><h2>Project Controls Viewer Tutorial</h2><span>Local-first • GitHub Pages • No project uploads</span></div><div class="panel-body"><p>This application is designed to behave like a browser-hosted planning workstation. The website is only the application; your XER, Microsoft Project XML and BIM model remain on the local computer.</p><div class="tutorial-grid"><button data-tut="schedule" class="primary">1. Open & edit a schedule</button><button data-tut="calc">2. Calculation settings & F9</button><button data-tut="wbs">3. WBS & activities</button><button data-tut="resources">4. Resource sheets & histograms</button><button data-tut="baseline">5. Baselines</button><button data-tut="bim">6. BIM / 4D workflow</button><button data-tut="navis">7. Navisworks exporter</button><button data-tut="advanced">8. Advanced controls</button></div></div></div><div id="tutorialContent" class="panel" style="margin-top:12px"></div></div>`}
export function bindTutorial(){const topics={schedule:topicSchedule,calc:topicCalc,wbs:topicWbs,resources:topicResources,baseline:topicBaseline,bim:topicBim,navis:topicNavis,advanced:topicAdvanced};const draw=k=>{document.querySelector('#tutorialContent').innerHTML=topics[k]();document.querySelectorAll('[data-tut]').forEach(b=>b.classList.toggle('active',b.dataset.tut===k));};document.querySelectorAll('[data-tut]').forEach(b=>b.onclick=()=>draw(b.dataset.tut));draw('schedule')}
function topicSchedule(){return `<div class="panel-head"><h3>1. Open, edit and save a schedule</h3></div><div class="panel-body"><ol><li>Open a P6 XER or Microsoft Project XML schedule, or drag it onto the page.</li><li>Select a project if the XER contains multiple projects.</li><li>Edit Activities, WBS, Relationships, Resources or Raw Tables.</li><li>Press <b>F9</b> to calculate the schedule.</li><li>Save as P6 XER, MSP XML, or download a Unified Schedule project package; the original file is never overwritten automatically.</li></ol><p><b>Tip:</b> Every edit is undoable. Use the Schedule Editor for safe P6-aware editing and Raw Tables only for specialist changes.</p></div>`}
function topicCalc(){return `<div class="panel-head"><h3>2. Scheduling settings and calculation options</h3></div><div class="panel-body"><p>The Settings page controls the calculation engine rather than changing the source XER format. Choose the compatibility profile first, then configure:</p><ul><li>Retained Logic / Progress Override / Actual Dates</li><li>Data Date and Expected Finish behaviour</li><li>Primary/secondary constraint handling</li><li>Lag calendar selection</li><li>Calendar exceptions and split shifts</li><li>External relationship policy</li><li>Resource leveling and capacity</li><li>Resource curves and strict validation</li></ul><p>Calculation settings can be exported as JSON so project standards are reusable.</p></div>`}
function topicWbs(){return `<div class="panel-head"><h3>3. WBS, activities and structure</h3></div><div class="panel-body"><p>The WBS view is a structural editor, not a visual grouping only.</p><ul><li>Add root, child or sibling WBS elements.</li><li>Rename, reparent and resequence hierarchy.</li><li>Duplicate a complete branch including activities.</li><li>Copy/paste branches with keyboard shortcuts.</li><li>Move activities directly between WBS nodes.</li><li>Store OBS, notebook text and EV fields at WBS level.</li></ul><p>Deleting a WBS always presents safe options so activities are not accidentally orphaned.</p></div>`}
function topicResources(){return `<div class="panel-head"><h3>4. Resource Sheet and Profiles</h3></div><div class="panel-body"><p><b>Resource Sheet</b> is intentionally a flat assignment table. Filter it, copy visible rows as tab-separated values and paste directly into Excel without reformatting.</p><p><b>Resource Profiles</b> provide daily, weekly and monthly histograms plus cumulative S-curves for budget, actual, remaining and forecast units or cost.</p><ol><li>Choose a resource or all resources.</li><li>Select bucket and units/cost.</li><li>Review histogram.</li><li>Review cumulative curve.</li><li>Expand the time-phased table if numerical values are needed.</li></ol></div>`}

function topicBaseline(){return `<div class="panel-head"><h3>5. Baseline management</h3></div><div class="panel-body"><ol><li>Open the current XER first.</li><li>Open <b>Baselines</b> and load one or more approved XER files.</li><li>Assign Project, Primary, Secondary or Tertiary roles. The Primary baseline drives Gantt baseline bars and default activity variance columns.</li><li>Review Start, Finish, Duration and Float variances. Positive date variance means the current schedule is later than baseline.</li><li>Use XER Compare separately when you need a detailed revision/change log rather than performance-to-plan.</li></ol></div>`}
function topicBim(){return `<div class="panel-head"><h3>5. Local BIM / 4D workflow</h3></div><div class="panel-body"><p><b>Goal:</b> link activities to BIM elements without uploading either file.</p><div class="tutorial-flow"><div>Open XER</div><span>→</span><div>Open local GLB</div><span>→</span><div>Load metadata JSON</div><span>→</span><div>Select activity + objects</div><span>→</span><div>Save XER</div></div><h4>What is stored where?</h4><table><tr><th>Data</th><th>Location</th></tr><tr><td>Activity ↔ BIM stable IDs</td><td>Native P6 Activity Text UDFs: BIM_LINK_01, BIM_LINK_02…</td></tr><tr><td>Geometry</td><td>Local GLB only</td></tr><tr><td>Properties, hierarchy, viewpoints</td><td>Local metadata JSON / optional .bimlink.json sidecar</td></tr><tr><td>4D settings</td><td>Sidecar / project workspace</td></tr></table><h4>Using the BIM Model tab</h4><ol><li>Open a local <code>.glb</code> file.</li><li>Load its matching metadata JSON generated by the exporter.</li><li>Rotate with left drag, pan with right drag and zoom with the wheel.</li><li>Select a BIM object; linked activities are highlighted.</li><li>Select an activity; choose <b>Show linked</b> or <b>Isolate linked</b>.</li><li>Use the simulation date to colour linked model elements as not started, active or complete.</li></ol><p><b>Critical rule:</b> links are stored using stable exported object identifiers, not transient viewer IDs, so model refreshes can be reconciled.</p></div>`}
function topicNavis(){return `<div class="panel-head"><h3>6. Navisworks exporter utility</h3></div><div class="panel-body"><p>The included exporter is a separate Visual Studio C# Navisworks plugin project. It is not required by the GitHub website at runtime.</p><ol><li>Install the plugin on a machine with Navisworks Manage/Simulate and the matching Autodesk .NET API.</li><li>Open the federated model.</li><li>Run <b>Export Project Controls Metadata</b>.</li><li>Choose an output folder.</li><li>Export the scene to FBX using Navisworks' standard exporter, then convert FBX to GLB using your preferred local converter if required.</li><li>Open the GLB and generated metadata JSON together in the GitHub application.</li></ol><p>The plugin emits stable object metadata, hierarchy and property sets. Geometry stays a local file. This deliberately avoids cloud services and keeps the project folder portable.</p><h4>Recommended project folder</h4><pre>Project/
├── schedule/current.xer
├── bim/model.glb
├── bim/model-metadata.json
├── links/Project.bimlink.json
└── settings/calculation-options.json</pre></div>`}

function topicAdvanced(){return `<div class="panel-head"><h3>8. Advanced project-controls workflow</h3></div><div class="panel-body"><ul><li><b>Layouts & Filters:</b> save column sets, grouping, timescale, sorting and P6-style AND/OR filters.</li><li><b>Logic Diagnostics:</b> select an activity to inspect visible date drivers and ranked multiple-float paths.</li><li><b>Progress & EVM:</b> import status CSV, validate progress, review PV/EV/AC/SPI/CPI/EAC/VAC and productivity.</li><li><b>History & Scenarios:</b> create revision snapshots, compare them, clone recovery scenarios and keep an audit trail.</li><li><b>Project Workspace:</b> autosave locally with IndexedDB and export a portable <code>.ussproj</code> package.</li><li><b>Calendars:</b> use exception overrides and split shifts; validate overlaps before scheduling.</li><li><b>BIM Advanced:</b> build property sets, apply rule-based links, review linked quantities and reconcile new model revisions by stable IDs.</li><li><b>Conversion audit:</b> cross-format XER/XML exports show a quality score and fidelity warnings before download.</li></ul><p>For contractual use, validate calculated dates and float against your organization’s approved P6/MSP golden schedules before relying on a new compatibility profile.</p></div>`}
