import test from 'node:test';import assert from 'node:assert/strict';import {parseGLB,taskBimColor} from '../src/bim-viewer.js';import {tutorialHTML} from '../src/tutorial.js';import fs from 'node:fs';
function glb(){const pos=new Float32Array([0,0,0,1,0,0,0,1,0]);const idx=new Uint16Array([0,1,2]);const bin=Buffer.concat([Buffer.from(pos.buffer),Buffer.from(idx.buffer)]);const json={asset:{version:'2.0'},buffers:[{byteLength:bin.length}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36},{buffer:0,byteOffset:36,byteLength:6}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3'},{bufferView:1,componentType:5123,count:3,type:'SCALAR'}],meshes:[{primitives:[{attributes:{POSITION:0},indices:1}]}],nodes:[{name:'Tri',mesh:0}],scenes:[{nodes:[0]}],scene:0};const jb=Buffer.from(JSON.stringify(json));const pad=b=>Buffer.concat([b,Buffer.alloc((4-b.length%4)%4,0x20)]);const jp=pad(jb),bp=Buffer.concat([bin,Buffer.alloc((4-bin.length%4)%4)]);const out=Buffer.alloc(12+8+jp.length+8+bp.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);let o=12;out.writeUInt32LE(jp.length,o);out.writeUInt32LE(0x4e4f534a,o+4);jp.copy(out,o+8);o+=8+jp.length;out.writeUInt32LE(bp.length,o);out.writeUInt32LE(0x004e4942,o+4);bp.copy(out,o+8);return out}
test('GLB parser loads a valid local glTF 2.0 binary scene',async()=>{const b=glb();const file={name:'tri.glb',arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};const s=await parseGLB(file);assert.equal(s.items.length,1);assert.equal(s.gltf.nodes[0].name,'Tri');assert.equal(s.items[0].indices.length,3)});
test('4D colour helper returns stable complete/in-progress/future states',()=>{const t={target_start_date:'2026-08-10',target_end_date:'2026-08-20',status_code:'TK_NotStart'};assert.deepEqual(taskBimColor(t,'2026-08-01'),[0.55,0.58,0.62,0.28]);assert.deepEqual(taskBimColor(t,'2026-08-15'),[0.96,0.62,0.12,1]);assert.deepEqual(taskBimColor({...t,status_code:'TK_Complete'},'2026-08-15'),[0.18,0.75,0.36,1])});
test('Tutorial includes dedicated BIM and Navisworks sections',()=>{const h=tutorialHTML();assert.match(h,/BIM \/ 4D workflow/);assert.match(h,/Navisworks exporter/)});
test('UI exposes BIM Model and Tutorial navigation',()=>{const h=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(h,/data-view="bimModel"/);assert.match(h,/data-view="tutorial"/)});
test('GLB parser rejects invalid magic',async()=>{const b=Buffer.alloc(20);const f={name:'bad.glb',arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};await assert.rejects(()=>parseGLB(f),/valid GLB/)});
test('GLB parser rejects missing BIN chunk',async()=>{const j=Buffer.from(JSON.stringify({asset:{version:'2.0'}}));const p=Buffer.concat([j,Buffer.alloc((4-j.length%4)%4)]);const out=Buffer.alloc(20+p.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(p.length,12);out.writeUInt32LE(0x4e4f534a,16);p.copy(out,20);const f={name:'x.glb',arrayBuffer:async()=>out.buffer.slice(out.byteOffset,out.byteOffset+out.byteLength)};await assert.rejects(()=>parseGLB(f),/JSON and BIN/)});
test('Future state colour is translucent while complete state is opaque green',()=>{const future=taskBimColor({target_start_date:'2030-01-01',target_end_date:'2030-01-02'},'2026-01-01');assert.equal(future[3],0.28);const done=taskBimColor({target_start_date:'2030-01-01',target_end_date:'2030-01-02',status_code:'TK_Complete'},'2026-01-01');assert.equal(done[3],1)});
test('Tutorial is copy-safe static HTML without script tags',()=>{assert.equal(/<script/i.test(tutorialHTML()),false)});
test('P6 code keeps BIM viewer isolated as a dedicated module',()=>{const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');assert.match(app,/from '\.\/bim-viewer\.js'/);assert.match(app,/renderBimModel/)});
test('GLB fixture bounds are finite and positive',async()=>{const b=glb();const s=await parseGLB({name:'tri.glb',arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)});assert.ok(Number.isFinite(s.bounds.diag));assert.ok(s.bounds.diag>0)});
