import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';
import {model} from './helpers/model.mjs';import {serializeXER} from '../src/serializer.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(new URL('..',import.meta.url).pathname);
const server=http.createServer(async(req,res)=>{try{let p=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname));if(p===root+path.sep)p=path.join(root,'index.html');res.setHeader('Content-Type',/\.m?js$/.test(p)?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.wasm')?'application/wasm':p.endsWith('.pdf')?'application/pdf':p.endsWith('.html')?'text/html':'text/plain');res.end(await fs.readFile(p))}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,args:process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):['--no-sandbox'],executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;console.log('PASS '+m)};const errors=[];
try{
 await fs.mkdir(path.join(root,'validation/v8'),{recursive:true});
 const page=await browser.newPage({viewport:{width:1600,height:1100},acceptDownloads:true});await page.addInitScript(()=>{window.showSaveFilePicker=undefined});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{if(d.type()==='alert')console.log('ALERT '+d.message());return d.type()==='prompt'?d.accept('critical activities'):d.accept()});
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.locator('#openBtn').waitFor();
 const fixture=model([{task_id:'1',task_code:'A',task_name:'Concrete',proj_id:'P',target_drtn_hr_cnt:'80',remain_drtn_hr_cnt:'40'},{task_id:'2',task_code:'B',task_name:'Pipework',proj_id:'P'},{task_id:'3',task_code:'A',task_name:'Baseline concrete',proj_id:'Q'}],[],{PROJECT:[{proj_id:'P',proj_short_name:'Current',last_recalc_date:'2026-01-05 08:00'},{proj_id:'Q',proj_short_name:'Baseline',last_recalc_date:'2025-12-01 08:00'}]});
 await page.locator('#fileInput').setInputFiles({name:'two-projects.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(fixture))});await page.waitForFunction(()=>document.querySelector('#fileStatus').textContent.includes('two-projects'));
 await page.locator('#nav [data-view="aiStudio"]').click();await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'),{},{timeout:60000});
 const frame=page.frameLocator('#toolkitFrame');const child=page.frames().find(f=>f.url().includes('/toolkit/'));
 check(await frame.locator('#scheduleList .schedule-row').count()===2,'separate viewer projects in shared repository');check(await frame.locator('#studioReference').inputValue()==='','baseline is not automatically inferred');check(await frame.locator('[data-output-card]').count()===4,'four Contract Manager outputs');check((await child.evaluate(()=>localStorage.getItem('studio8.ai.model')))===null,'AI remains off by default');
 for(const type of ['report','graphic','data','audio']){await frame.locator(`[data-nb-create="${type}"]`).click();await frame.locator(`[data-nb-download="${type}"]`).waitFor();check((await frame.locator(`#nb-${type}-preview`).innerText()).length>0||await frame.locator(`#nb-${type}-preview svg`).count()>0,`Contract ${type} output`)}
 await page.screenshot({path:path.join(root,'validation/v8/contracts.png'),fullPage:true});
 await page.locator('#nav [data-view="reportStudio"]').click();const reportIds=await page.locator('#reportChoice option').evaluateAll(xs=>xs.map(x=>x.value).filter(x=>x.startsWith('toolkit:')));
 for(const id of reportIds){await page.locator('#reportChoice').selectOption(id);await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'),{},{timeout:60000});check((await frame.locator('#reportBody').innerText()).length>10,'report renders '+id)}
 check(await frame.locator('.report-nav').count()===0,'no duplicate report buttons');
 await page.locator('#reportChoice').selectOption('nodes');await page.locator('#nodePred').selectOption('1');await page.locator('#nodeSucc').selectOption('2');await page.locator('#nodeSave').click();check(await page.locator('#nodeRelationship option').count()===2,'Nodes adds dependency');await page.locator('#nodePred').selectOption('2');await page.locator('#nodeSucc').selectOption('1');await page.locator('#nodeSave').click();check((await page.locator('#nodeFeedback').innerText()).includes('cycle'),'Nodes rejects cycle without mutation');
 const node=page.locator('[data-node="1"] rect');const box=await node.boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.mouse.move(box.x+80,box.y+65);await page.mouse.up();check(await page.evaluate(()=>JSON.parse(localStorage.getItem('studio8.nodes:two-projects.xer:P'))['1'].x>30),'dragged node position persisted');
 await page.locator('#reportChoice').selectOption('contract');await page.locator('#contractSource').fill('Example client requirements');await page.locator('#contractClause').fill('2.1');await page.locator('#contractAdd').click();check((await page.locator('#view').innerText()).includes('Not adopted'),'unapproved contract profile not treated as pass');await page.locator('#contractAdopted').check();await page.locator('#contractSave').click();check((await page.locator('#view table').innerText()).includes('Pass'),'adopted contractual rule assessed');
 await page.locator('#nav [data-view="aiStudio"]').click();await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));
 for(const module of ['manpower','risk','claims','builder','settings','drawing']){await page.locator('#aiModuleChoice').selectOption(module);await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));check((await frame.locator('#workspace').innerText()).length>100,'AI module '+module)}

 check(await page.locator('#toolkitHost>p').isHidden(),'completed synchronization occupies no visible row');
 await fs.mkdir(path.join(root,'validation/v802'),{recursive:true});
 check(await frame.locator('#calibratedTakeoff fieldset').count()===3,'drawing controls grouped into three labelled sections');
 await frame.locator('#calibratedTakeoff').screenshot({path:path.join(root,'validation/v802/drawing-controls.png')});
 await page.setViewportSize({width:900,height:1000});
 check(await frame.locator('#calibratedTakeoff').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'drawing form fits narrower workspace without horizontal overflow');
 await page.setViewportSize({width:1600,height:1100});
 await page.locator('#nav [data-view="reportStudio"]').click();await page.locator('#reportChoice').selectOption('toolkit:dcma');
 await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));
 check(await frame.locator('#chatInput,#chatSend,input[type=password]').count()===0,'Reports contains no AI chat or credential controls');
 const blocked=await child.evaluate(async()=>{
  const cloud=await import('./src/ai/cloud.js'),ollama=await import('./src/ai/ollama.js'),browser=await import('./src/ai/browser.js'),runtime=await import('./src/ai/runtime.js');
  cloud.saveCloudConfig('custom',{apiKey:'synthetic-key',model:'test',baseUrl:'https://example.invalid'});
  const saved=fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('unexpected network')};const messages=[];
  try{for(const run of [()=>cloud.cloudChat('custom',[]),()=>ollama.chat([]),()=>browser.browserCPU([]),()=>runtime.askAI({question:'test'})]){try{await run();messages.push('allowed')}catch(e){messages.push(e.message)}}return {calls,messages};}finally{globalThis.fetch=saved;cloud.clearCloudKey('custom')}
 });
 check(blocked.calls===0&&blocked.messages.every(m=>m.includes('only in AI Studio')),'cloud, Ollama, browser model and AI runtime blocked from Reports before network calls');
 await page.locator('#nav [data-view="activities"]').click();
 check(await child.evaluate(async()=>{try{(await import('./src/ai/scope.js')).assertAIStudioScope();return false}catch{return true}}),'hidden AI workspace cannot initiate AI from Activities');
 await page.locator('#nav [data-view="aiStudio"]').click();await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));
 await frame.locator('#fileInput').setInputFiles(path.join(root,'tests/fixtures/takeoff.pdf'));await frame.locator('.repo-file').filter({hasText:'takeoff.pdf'}).waitFor();
 // Re-enter to make the new repository file available to take-off controls.
 await page.locator('#aiModuleChoice').selectOption('contracts');await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));await page.locator('#aiModuleChoice').selectOption('drawing');await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));
 const pdfId=await frame.locator('#takeoffDrawing option').filter({hasText:'takeoff.pdf'}).getAttribute('value');await frame.locator('#takeoffDrawing').selectOption(pdfId);await frame.locator('#takeoffOpen').click();await frame.locator('#takeoffStatus').filter({hasText:'Opened takeoff.pdf'}).waitFor({timeout:60000});check(await frame.locator('#takeoffCanvas').evaluate(c=>c.width>500),'PDF rendered locally');
 await frame.locator('#takeoffRequest').fill('metres of piping');await frame.locator('#takeoffKnown').fill('10');await frame.locator('#takeoffOverlay').click({position:{x:100,y:100}});await frame.locator('#takeoffOverlay').click({position:{x:400,y:100}});await frame.locator('#takeoffCalibrate').click();await frame.locator('#takeoffOverlay').click({position:{x:100,y:200}});await frame.locator('#takeoffOverlay').click({position:{x:400,y:200}});await frame.locator('#takeoffCommit').click();check((await frame.locator('#takeoffStatus').innerText()).includes('10.000000'),'calibrated 10 metre quantity');
 const auditDownload=page.waitForEvent('download');await frame.locator('#exportTakeoffAudit').click();const download=await auditDownload;const audit=JSON.parse(await fs.readFile(await download.path(),'utf8'));check(audit.length===1&&audit[0].quantity===10&&audit[0].trace.sha256.length===64,'quantity export retains calibration and source hash');
 const backup=await child.evaluate(async()=>await (await import('./src/repository/backup.js')).exportAIWorkspace());check(backup.files.length===1&&backup.prefs.quantities.includes('measuredQuantity'),'backup contains document bytes and measured rows');
 const restored=await child.evaluate(async data=>{const m=await import('./src/repository/backup.js');await m.importAIWorkspace(data);return await m.exportAIWorkspace()},backup);check(restored.files[0].data===backup.files[0].data&&JSON.parse(restored.prefs.quantities)[0].quantity===10,'AI backup restores evidence and quantities');
 await page.screenshot({path:path.join(root,'validation/v8/drawing.png'),fullPage:true});
 // Synthetic provider transport: never send project data to a live cloud provider.
 const ollama=await child.evaluate(async()=>{const {chat}=await import('./src/ai/ollama.js');const saved=globalThis.fetch;let body;globalThis.fetch=async(url,options)=>{body=JSON.parse(options.body);return new Response(JSON.stringify({message:{content:'mock provider response'}}),{status:200,headers:{'content-type':'application/json'}})};try{return {result:await chat([{role:'user',content:'test only'}],{model:'mock'}),body}}finally{globalThis.fetch=saved}});check(JSON.stringify(ollama).includes('mock provider response'),'Ollama transport with mocked response');
 await page.locator('#nav [data-view="activities"]').click();await page.locator('#menuBar > details').first().locator('summary').click();await page.locator('[data-command="saveAs"]').click();await page.locator('#saveAsFormat').selectOption('package');await page.locator('#saveAsCalculation').selectOption('current');const packageDownload=page.waitForEvent('download');await page.locator('#saveAsWrite').click();const pkgFile=await packageDownload;const pkgPath=await pkgFile.path(),pkg=JSON.parse(await fs.readFile(pkgPath,'utf8'));check(pkg.aiWorkspace?.files.length===1&&Object.keys(pkg.studioLocal).length>=2,'Save As package includes AI evidence, Nodes layout and contract profile');
 await page.locator('#packageInput').setInputFiles({name:'roundtrip.ussproj',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});await page.waitForFunction(()=>document.querySelector('#projectSelect option')?.textContent==='Current');await page.locator('#nav [data-view="aiStudio"]').click();await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'));check(await frame.locator('.repo-file').filter({hasText:'takeoff.pdf'}).count()===1,'project package restores AI evidence');
 await page.evaluate(()=>{window.showSaveFilePicker=async()=>({name:'native-copy.ussproj',createWritable:async()=>({write:async text=>{window.testNativePackage=text},close:async()=>{}})})});
 await page.locator('#nav [data-view="activities"]').click();await page.locator('#menuBar > details').first().locator('summary').click();await page.locator('[data-command="saveAs"]').click();await page.locator('#saveAsFormat').selectOption('package');await page.locator('#saveAsCalculation').selectOption('current');await page.locator('#saveAsWrite').click();await page.waitForFunction(()=>!!window.testNativePackage);check(await page.evaluate(()=>JSON.parse(window.testNativePackage).aiWorkspace.files.length===1),'native save adapter writes a complete evidence package');
 await page.evaluate(()=>{window.showSaveFilePicker=async()=>{throw new DOMException('Cancelled','AbortError')}});await page.locator('#menuBar > details').first().locator('summary').click();await page.locator('[data-command="saveAs"]').click();await page.locator('#saveAsFormat').selectOption('package');await page.locator('#saveAsCalculation').selectOption('current');await page.locator('#saveAsWrite').click();check(await page.locator('#modal').evaluate(x=>x.open),'native cancellation leaves Save As open without fallback download');await page.locator('#saveAsCancel').click();
 check(errors.length===0,'no browser runtime errors: '+errors.join('; '));console.log(`Browser v8 PASS: ${checks} checks.`);
}finally{await browser.close();server.close()}
