import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';
import {model} from './helpers/model.mjs';import {serializeXER} from '../src/serializer.js';import {exportMSPXML} from '../src/format-adapters.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(new URL('..',import.meta.url).pathname),publicRoot=path.join(root,'dist'),prefix='/schedule-studio/';
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');if(!url.pathname.startsWith(prefix))throw Error('Outside deployment');let rel=decodeURIComponent(url.pathname.slice(prefix.length))||'index.html';const p=path.resolve(publicRoot,rel);if(!p.startsWith(publicRoot+path.sep))throw Error('Outside root');res.setHeader('Content-Type',/\.m?js$/.test(p)?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.wasm')?'application/wasm':p.endsWith('.html')?'text/html':'application/octet-stream');res.end(await fs.readFile(p));}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,base=origin+prefix,browser=await chromium.launch({headless:true,args:process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):['--no-sandbox'],executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});let checks=0;const check=(ok,label)=>{assert.ok(ok,label);console.log('PASS '+label);checks++};
try{
 const page=await browser.newPage({acceptDownloads:true,viewport:{width:1600,height:1100}}),errors=[],external=[];
 await page.addInitScript(()=>{window.showSaveFilePicker=undefined});
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/*',route=>{const url=route.request().url();if(/^https?:/.test(url)&&!url.startsWith(origin+'/')){external.push(url);return route.abort()}return route.continue()});
 await page.goto(base);await page.locator('#openBtn').waitFor();
 const chooserPromise=page.waitForEvent('filechooser');await page.locator('#openBtn').click();const chooser=await chooserPromise;check(chooser.isMultiple(),'Open offers multiple-file selection');
 const make=(name)=>model([{task_id:'1',task_code:'A',task_name:name+' activity A',proj_id:'P'},{task_id:'2',task_code:'B',task_name:name+' activity B',proj_id:'P'}],[],{PROJECT:[{proj_id:'P',proj_short_name:name,last_recalc_date:'2026-01-05 08:00'}]});
 const a=make('First'),b=make('Second'),c=make('Third');
 await chooser.setFiles([{name:'first.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(a))},{name:'invalid.xml',mimeType:'application/xml',buffer:Buffer.from('not a schedule')},{name:'second.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(b))},{name:'third.xml',mimeType:'application/xml',buffer:Buffer.from(exportMSPXML(c,'P'))}]);
 await page.locator('#importSummary').filter({hasText:'Opened 3 of 4 files'}).waitFor({timeout:60000});
 check(await page.locator('#documentSelect option').count()===3,'mixed XER/XML batch retains every valid file');check((await page.locator('#importSummary').innerText()).includes('invalid.xml'),'failed file identified without stopping batch');check(await page.locator('#projectSelect').inputValue()==='P','first valid file remains active');check((await page.locator('#activityTable').innerText()).includes('First activity'),'first file parsed correctly');
 const ids=await page.locator('#documentSelect option').evaluateAll(xs=>xs.map(x=>x.value));
 await page.locator('#nav [data-view="reportStudio"]').click();await page.locator('#reportChoice').selectOption('nodes');await page.locator('#nodePred').selectOption('1');await page.locator('#nodeSucc').selectOption('2');await page.locator('#nodeSave').click();check(await page.locator('#nodeRelationship option').count()===2,'edit first file dependency');
 await page.locator('#documentSelect').selectOption(ids[1]);await page.locator('#reportChoice').selectOption('nodes');check(await page.locator('#nodeRelationship option').count()===1,'same IDs in second file do not inherit first file edits');await page.locator('#nav [data-view="activities"]').click();check((await page.locator('#activityTable').innerText()).includes('Second activity'),'second file retains independent model');check((await page.locator('#fileStatus').innerText()).startsWith('second.xer'),'status identifies selected file after switching');
 await page.locator('#documentSelect').selectOption(ids[2]);check((await page.locator('#activityTable').innerText()).includes('Third activity'),'XML file parsed and selectable');
 await page.locator('#documentSelect').selectOption(ids[0]);check((await page.locator('#crumb').innerText()).includes('F9 required'),'pending calculation follows edited file');await page.locator('#nav [data-view="reportStudio"]').click();await page.locator('#reportChoice').selectOption('nodes');check(await page.locator('#nodeRelationship option').count()===2,'edit survives switching among files');
 await page.keyboard.press('Control+z');check(await page.locator('#nodeRelationship option').count()===1,'undo history survives file switching');await page.keyboard.press('Control+y');check(await page.locator('#nodeRelationship option').count()===2,'redo history survives file switching');
 // Export the active file only and verify that similarly numbered projects are not merged.
 await page.locator('#menuBar > details').first().locator('summary').click();await page.locator('[data-command="saveAs"]').click();await page.locator('#saveAsFormat').selectOption('xer');await page.locator('#saveAsCalculation').selectOption('current');const event=page.waitForEvent('download');await page.locator('#saveAsWrite').click();const download=await event,text=await fs.readFile(await download.path(),'utf8');check(text.includes('First activity')&&!text.includes('Second activity'),'Save As exports the selected file without cross-file contamination');
 await page.locator('#nav [data-view="aiStudio"]').click();await page.waitForFunction(()=>document.querySelector('#toolkitHost>p')?.textContent.startsWith('Schedule snapshots synchronised'),{},{timeout:60000});const frame=page.frameLocator('#toolkitFrame');check(await frame.locator('#scheduleList .schedule-row').count()===3,'AI repository receives all opened schedules');await page.locator('#aiModuleChoice').selectOption('settings');await frame.locator('#settingsAiSelect').waitFor();check(await frame.locator('#mppBridgeUrl').count()===0,'native MPP installer removed');check(await frame.locator('input[type=password]').count()===7,'personal provider key fields available');check(external.length===0,'opening schedules and settings invokes no AI or external service');
 // Browser-only provider failure must remain actionable without requiring installed software.
 const child=page.frames().find(f=>f.url().includes('/toolkit/'));const blocked=await child.evaluate(async()=>{const m=await import('./src/ai/cloud.js');m.saveCloudConfig('custom',{apiKey:'synthetic-test-key',model:'test',baseUrl:'https://invalid.example/v1/chat/completions'});const original=fetch;globalThis.fetch=async()=>{throw new TypeError('Failed to fetch')};try{return await m.testCloudAI('custom')}finally{globalThis.fetch=original;m.clearCloudKey('custom')}});check(!blocked.ok&&blocked.message.includes('CORS'),'direct-provider network/CORS failure explained');
 if(process.env.DWG_FIXTURE){const bytes=Array.from(await fs.readFile(process.env.DWG_FIXTURE));const result=await page.evaluate(bytes=>new Promise((resolve,reject)=>{const worker=new Worker(new URL('./toolkit/src/measurement/dwg-worker.js',location.href),{type:'module'});const timer=setTimeout(()=>{worker.terminate();reject(Error('timeout'))},60000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();resolve(e.data)};worker.onerror=e=>{clearTimeout(timer);worker.terminate();reject(Error(e.message))};const data=Uint8Array.from(bytes).buffer;worker.postMessage(data,[data])}),bytes);check(!result.error&&/<svg/.test(result.svg),'deployed DWG decoder works at repository subpath');}
 await page.locator('#nav [data-view="activities"]').click();await page.locator('#fileInput').setInputFiles([{name:'broken.xml',mimeType:'application/xml',buffer:Buffer.from('broken')},{name:'unsupported.mpp',mimeType:'application/octet-stream',buffer:Buffer.from('bad')}]);await page.locator('#importSummary').filter({hasText:'Opened 0 of 2 files'}).waitFor();check(await page.locator('#documentSelect option').count()===3,'all-invalid batch preserves open documents');check((await page.locator('#activityTable').innerText()).includes('First activity'),'invalid batch leaves current schedule intact');
 await page.locator('#fileInput').setInputFiles({name:'first.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(b))});await page.waitForFunction(()=>document.querySelectorAll('#documentSelect option').length===4);check((await page.locator('#activityTable').innerText()).includes('Second activity'),'same filename can contain a distinct schedule without overwriting earlier edits');await page.locator('#documentSelect').selectOption(ids[0]);check((await page.locator('#activityTable').innerText()).includes('First activity'),'original same-name schedule still available');
 await fs.mkdir(path.join(root,'validation/v801'),{recursive:true});await page.screenshot({path:path.join(root,'validation/v801/multiple-files.png'),fullPage:true});
 check(errors.length===0,'no browser runtime errors: '+errors.join('; '));check(external.length===0,'browser operation needs no localhost or external backend');console.log(`Pages browser PASS: ${checks} checks.`);
}finally{await browser.close();server.close()}
