// npm install --no-save playwright; npx playwright install chromium; npm run test:browser
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';
import {model} from './helpers/model.mjs';import {serializeXER} from '../src/serializer.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(new URL('..',import.meta.url).pathname);const server=http.createServer(async(req,res)=>{try{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname));const p=file===root+path.sep?path.join(root,'index.html'):file;res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':'text/plain');res.end(await fs.readFile(p));}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const args=process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):['--no-sandbox'];const browser=await chromium.launch({headless:true,args,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});
const errors=[],dialogs=[];let checks=0;const check=(value,message)=>{assert.ok(value,message);checks++};
try{const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.message());await d.dismiss()});await page.goto(`http://127.0.0.1:${server.address().port}/?demo=1`);await page.locator('.activity-resizable-table').waitFor();
const tasks=Array.from({length:35},(_,i)=>({task_id:String(i+1),task_code:i?'A'+i:'LONG_ACTIVITY_ID_'.repeat(6),task_name:'Concrete foundations and installation '+('with a long description '.repeat(i?1:15)),wbs_id:i%2?'L4':'L3',target_drtn_hr_cnt:'80.25',remain_drtn_hr_cnt:'40',phys_complete_pct:'49.6',total_float_hr_cnt:i%3?'16':'0',status_code:i%3===0?'TK_NotStart':i%3===1?'TK_Active':'TK_Complete',target_start_date:'2026-01-01 08:00',target_end_date:'2026-02-12 17:00',early_start_date:'2026-01-01 08:00',early_end_date:'2026-02-12 17:00',act_start_date:i%3?'2026-01-01 08:00':'',act_end_date:i%3===2?'2026-01-04 17:00':''}));const wbs=Array.from({length:4},(_,i)=>({wbs_id:'L'+(i+1),parent_wbs_id:i?'L'+i:'',proj_id:'P',wbs_name:['Project','Civil works','Foundations','Concrete'][i]}));const assignments=tasks.map(t=>({taskrsrc_id:t.task_id,task_id:t.task_id,rsrc_id:'R',target_qty:'123.456789',act_reg_qty:'17.123456',remain_qty:'106.333333'}));const fixture=model(tasks,[],{PROJWBS:wbs,TASKRSRC:assignments,RSRC:[{rsrc_id:'R',rsrc_short_name:'Crew',rsrc_name:'Crew'}]});const data=serializeXER(fixture);await page.locator('#fileInput').setInputFiles({name:'acceptance.xer',mimeType:'text/plain',buffer:Buffer.from(data)});await page.waitForFunction(()=>document.querySelectorAll('.activity-resizable-table tbody tr[data-id]').length===35);
check(await page.locator('.activity-inline-edit.duration').first().inputValue()==='81','duration ceiling');check(await page.locator('.activity-inline-edit.pct').first().inputValue()==='50','percentage integer');check(!(await page.locator('.activity-percent-editor').first().innerText()).includes('%'),'percent has no symbol');
await page.locator('.activity-filter-menu summary').click();await page.locator('[data-activity-filter="active"]').check();check(await page.locator('.activity-resizable-table tbody tr[data-id]').count()===12,'active filter');await page.locator('[data-activity-filter="critical"]').check();check(await page.locator('.activity-resizable-table tbody tr[data-id]').count()===24,'OR filter');await page.locator('[data-activity-filter="all"]').check();check(await page.locator('.activity-resizable-table tbody tr[data-id]').count()===35,'all filter');await page.locator('.activity-filter-menu summary').click();
check(await page.locator('.gantt-body .data-date-line').count()===1,'body data date');await page.locator('#activityDataDate').uncheck();check(await page.locator('.data-date-line').count()===0,'hide data date');await page.locator('#activityDataDate').check();check(await page.locator('.gantt-body .data-date-line').evaluate(e=>getComputedStyle(e).borderLeftStyle)==='dashed','dashed data date');await page.locator('#activityWrap').check();await page.waitForTimeout(200);const sizes=await page.evaluate(()=>{const a=[...document.querySelectorAll('#activityTable tbody tr')],g=[...document.querySelectorAll('.gantt-body>div')];return a.map((r,i)=>[r.getBoundingClientRect().height,g[i]?.getBoundingClientRect().height])});check(sizes.every(([a,b])=>Math.abs(a-b)<2),'wrapped grid/Gantt alignment');check(sizes.some(([a])=>a>50),'description wraps');await page.locator('.activity-filter-menu summary').click();await page.locator('[data-activity-filter="all"]').uncheck();check(await page.locator('.activity-resizable-table').count()===0,'empty wrapped filter does not crash');await page.locator('[data-activity-filter="all"]').check();await page.locator('.activity-filter-menu summary').click();check(await page.locator('td[data-col-key="task_code"]').first().evaluate(e=>getComputedStyle(e).overflow)==='hidden','IDs clipped');
await fs.mkdir(path.join(root,'validation/v710'),{recursive:true});await page.screenshot({path:path.join(root,'validation/v710/activities.png'),fullPage:true});
await page.locator('#nav [data-view="progressIntel"]').click();check((await page.locator('#view').innerText()).includes('Civil works'),'WBS names');const handle=page.locator('th .report-resizer').last();const before=await handle.evaluate(e=>e.closest('th').getBoundingClientRect().width);await handle.focus();await handle.press('ArrowRight');const after=await handle.evaluate(e=>e.closest('th').getBoundingClientRect().width);check(after>before,'columns keyboard resize');
await page.locator('#nav [data-view="reportStudio"]').click();const options=await page.locator('#reportChoice option').evaluateAll(es=>es.map(e=>e.value));for(const id of options){await page.locator('#reportChoice').selectOption(id);check((await page.locator('#view').innerText()).length>30,'report '+id);check(await page.locator('#reportChoice').count()===1,'selector persists '+id);}
await page.locator('#reportChoice').selectOption('evm');check((await page.locator('#view').innerText()).includes('Productivity by WBS'),'productivity report');check(await page.locator('.wbs-report-name').count()>=8,'EVM and productivity parent summaries');await page.locator('#reportChoice').selectOption('lookahead6');check((await page.locator('#view').innerText()).includes('Civil works'),'lookahead hierarchy');await page.locator('#reportChoice').selectOption('level4');check((await page.locator('#view').innerText()).includes('Concrete'),'Level 4 WBS');await page.screenshot({path:path.join(root,'validation/v710/progress-level4.png'),fullPage:true});
await page.locator('#reportChoice').selectOption('profiles');const counts=[];for(const b of ['day','week','month']){await page.locator('#profileBucket').selectOption(b);counts.push(await page.locator('.resource-audit-table tbody tr').count());check(await page.locator('.resource-chart svg').count()===2,'charts '+b);}check(counts[0]>counts[1]&&counts[1]>counts[2],'time buckets change table');
await page.locator('#profileHGrid').check();await page.locator('#profileVGrid').check();check(await page.locator('.resource-grid').count()>10,'gridlines render');await page.locator('#profileVertical').fill('150');await page.locator('#profileVertical').dispatchEvent('input');check(await page.locator('#resourceCurve svg').evaluate(e=>e.style.height)==='510px','vertical compression');
const dlPromise=page.waitForEvent('download');await page.locator('#profileCsv').click();const dl=await dlPromise;const csv=await fs.readFile(await dl.path(),'utf8');check(/\.\d{4}/.test(csv),'CSV preserves precision');check(!(await page.locator('.resource-audit-table tbody tr').first().innerText()).includes('.'),'table rounds integers');
const baseTotals=await page.locator('.resource-audit-table tbody tr').evaluateAll(rs=>rs.reduce((s,r)=>[s[0]+Number(r.cells[1].dataset.rawValue),s[1]+Number(r.cells[2].dataset.rawValue)],[0,0]));const copied=await page.locator('.resource-audit-table tbody tr td').nth(1).evaluate(td=>{const range=document.createRange();range.selectNodeContents(td);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);const data=new DataTransfer();td.dispatchEvent(new ClipboardEvent('copy',{bubbles:true,cancelable:true,clipboardData:data}));return [data.getData('text/plain'),td.dataset.rawValue]});check(copied[0]===copied[1],'selected cells copy full precision');await page.locator('#profileAlternatePlan').check();check((await page.locator('#view').innerText()).includes('Planned values are hidden'),'missing baseline explicit');const chooser=page.waitForEvent('filechooser');await page.locator('#profilePlanLoad').click();const fc=await chooser;const planned=model(tasks,[],{PROJWBS:wbs,TASKRSRC:assignments.map(r=>({...r,target_qty:'246.913578'})),RSRC:[{rsrc_id:'R',rsrc_short_name:'Crew',rsrc_name:'Crew'}]});await fc.setFiles({name:'planned.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(planned))});await page.waitForFunction(()=>document.querySelector('#profilePlanSource')?.value==='file:P');check(await page.locator('#profileAlternatePlan').isChecked(),'alternate planned loaded');const alternateTotals=await page.locator('.resource-audit-table tbody tr').evaluateAll(rs=>rs.reduce((s,r)=>[s[0]+Number(r.cells[1].dataset.rawValue),s[1]+Number(r.cells[2].dataset.rawValue)],[0,0]));check(Math.abs(alternateTotals[0]-2*baseTotals[0])<1e-7,'planned source changes budget');check(Math.abs(alternateTotals[1]-baseTotals[1])<1e-7,'planned source preserves actual');await page.screenshot({path:path.join(root,'validation/v710/resource-reports.png'),fullPage:true});
await page.locator('#reportChoice').selectOption('curve');check(await page.locator('#resourceHistogram').isHidden(),'S-curve only');await page.locator('#profileBucket').selectOption('week');check(await page.locator('#resourceHistogram').isHidden(),'S-curve selection survives changes');await page.locator('#reportChoice').selectOption('histogram');check(await page.locator('#resourceCurve').isHidden(),'histogram only');
check(await page.locator('#nav [data-view="resourceProfiles"]').count()===0,'resources tab removed');check(await page.locator('#menuBar [data-view="dashboard"],#nav [data-view="dashboardStudio"]').count()===0,'dashboard removed');
await page.locator('#nav [data-view="activities"]').click();await page.locator('#menuBar > details').first().locator('summary').click();await page.locator('[data-command="saveAs"]').click();await page.locator('#saveAsName').fill('acceptance-copy');await page.locator('#saveAsFormat').selectOption('package');check(await page.locator('#saveAsName').inputValue()==='acceptance-copy.ussproj','Save As extension');await page.locator('#saveAsCancel').click();
check(errors.length===0,'No runtime errors: '+errors.join('\n'));check(dialogs.length===0,'No unexpected dialogs: '+dialogs.join('\n'));console.log(`Browser 7.1.0 PASS: ${checks} assertions, ${options.length} report selections, real Chromium interactions and 3 screenshots.`);
}finally{await browser.close();server.close();}
