import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';
import {model} from './helpers/model.mjs';import {serializeXER} from '../src/serializer.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(new URL('..',import.meta.url).pathname);
const server=http.createServer(async(req,res)=>{try{let p=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname));if(p===root+path.sep)p=path.join(root,'index.html');res.setHeader('Content-Type',/\.m?js$/.test(p)?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.wasm')?'application/wasm':p.endsWith('.pdf')?'application/pdf':p.endsWith('.html')?'text/html':'text/plain');res.end(await fs.readFile(p))}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,args:process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):['--no-sandbox'],executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;console.log('PASS '+m)};const errors=[];
try{

 const context=await browser.newContext({viewport:{width:1600,height:1100},acceptDownloads:true});const page=await context.newPage();await page.addInitScript(()=>{window.showSaveFilePicker=undefined});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(`http://127.0.0.1:${server.address().port}/`);
 const fixture=model([{task_code:'A1',task_name:'Pipework',wbs_id:'W',target_drtn_hr_cnt:'24',remain_drtn_hr_cnt:'24',target_start_date:'2026-01-05 08:00',target_end_date:'2026-01-07 17:00'},{task_code:'A2',task_name:'Testing',wbs_id:'W',target_drtn_hr_cnt:'24',remain_drtn_hr_cnt:'24',target_start_date:'2026-01-08 08:00',target_end_date:'2026-01-12 17:00'}],[{pred_task_id:'1',task_id:'2',task_pred_id:'R'}],{PROJWBS:[{wbs_id:'W',proj_id:'P',parent_wbs_id:'EPS',proj_node_flag:'Y',wbs_short_name:'ROOTCODE',wbs_name:'Project description'}],ACTVTYPE:[{actv_code_type_id:'T1',actv_code_type:'Area'},{actv_code_type_id:'T2',actv_code_type:'Trade'}],ACTVCODE:[{actv_code_id:'C1',actv_code_type_id:'T1',short_name:'ZONE',actv_code_name:'Zone One'},{actv_code_id:'C2',actv_code_type_id:'T2',short_name:'MECH',actv_code_name:'Mechanical'}],TASKACTV:[{task_id:'1',actv_code_id:'C1'},{task_id:'2',actv_code_id:'C1'},{task_id:'1',actv_code_id:'C2'}]});
 await page.locator('#fileInput').setInputFiles([{name:'current.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(fixture))},{name:'other.xer',mimeType:'text/plain',buffer:Buffer.from(serializeXER(fixture))}]);await page.waitForFunction(()=>document.querySelector('#documentSelect')?.options.length===2&&!document.querySelector('#documentSelect').disabled);
 check((await page.locator('.activity-group-label').first().innerText()).includes('Project description'),'WBS description displayed');check(!(await page.locator('.activity-group-label').first().innerText()).includes('ROOTCODE'),'WBS code hidden');check(await page.locator('.activity-group-label small').count()===0,'WBS counts hidden');check((await page.locator('#activityBandTheme option[value="classic"]').innerText())==='Yellow','Classic renamed Yellow');await page.locator('#activityBandTheme').selectOption('mixed');check(await page.locator('.bands-mixed').count()===1,'Mixed palette selectable');const colors=await page.evaluate(()=>Array.from({length:8},(_,i)=>{const tr=document.createElement('tr');tr.className='wbs-band mixed-level-'+i;const td=document.createElement('td');tr.append(td);document.querySelector('#activityTable tbody').append(tr);const color=getComputedStyle(td).backgroundColor;tr.remove();return color}));check(new Set(colors).size===8,'eight distinct mixed band colours');await page.locator('#activityBandTheme').selectOption('blue');check(await page.locator('.bands-blue').count()===1,'band palette applied');
 await page.locator('#nav [data-view="aiStudio"]').click();const frame=page.frameLocator('#toolkitFrame');await frame.locator('.repository').waitFor({state:'visible'});check(await frame.locator('.repository').isVisible(),'AI Studio repository visible');await page.locator('#nav [data-view="reportStudio"]').click();await page.locator('#reportChoice').selectOption('toolkit:dcma');await frame.locator('body.studio-report-mode').waitFor();await frame.locator('.repository').waitFor({state:'hidden'});check(await frame.locator('.repository').isHidden(),'Reports repository hidden');
 for(const reportId of ['progress-integrity','floatpaths','dcma','whymove','delay','forensic','windows','calendar','forecast','timemachine','milestones','resourceforensics']){
 await page.locator('#reportChoice').selectOption('toolkit:'+reportId);
 await frame.locator('html[data-studio-report="'+reportId+'"]').waitFor();
 check(await frame.locator('#workspace').evaluate(el=>{const shell=el.parentElement.getBoundingClientRect(),box=el.getBoundingClientRect();return box.width>=shell.width-2&&Math.abs(box.x-shell.x)<2}),'full-width report: '+reportId);
 check(await frame.locator('.repository').isHidden(),'no repository: '+reportId);
 }
 await page.setViewportSize({width:850,height:1000});check(await frame.locator('#workspace').evaluate(el=>el.getBoundingClientRect().width>=el.parentElement.getBoundingClientRect().width-2),'report uses full width at narrow viewport');await page.setViewportSize({width:1600,height:1100});
 await page.locator('#nav [data-view="aiStudio"]').click();await frame.locator('.repository').waitFor({state:'visible'});check(await frame.locator('#workspace').evaluate(el=>el.getBoundingClientRect().x>=280),'AI repository and workspace restored');
 await page.locator('#nav [data-view="reportStudio"]').click();await page.locator('#reportChoice').selectOption('risk');await page.locator('#v7RiskIterations').fill('100');for(const id of ['v7RiskMin','v7RiskMode','v7RiskMax'])await page.locator('#'+id).fill('1');await page.locator('#v7RiskMax').press('Tab');
 await page.locator('#riskPasteText').fill('Risk ID\tDescription\tProbability %\tActivity codes\tMinimum hours\tMost likely hours\tMaximum hours\nR1\tShared delivery\t100\tA1;A2\t24\t24\t24'.replaceAll('\\t','\t').replaceAll('\\n','\n'));
 await page.locator('#riskPaste').click();check(await page.locator('[data-risk-cell]').count()===7,'risk register pasted into editable cells');await page.locator('#riskTargetDays').fill('3');await page.locator('#v7RunRisk').click();await page.locator('#riskDownloadReport').waitFor({timeout:60000});check((await page.locator('.risk-metrics').innerText()).includes('4 d'),'shared event changes project result');check(await page.locator('.risk-charts svg').count()===2,'distribution and CDF rendered');const download=page.waitForEvent('download');await page.locator('#riskDownloadReport').click();const report=await download;const html=await fs.readFile(await report.path(),'utf8');check(html.includes('Risk-event outcomes'),'graphic report downloadable');check(await page.locator('.risk-gauge svg').count()===3,'three assessment gauges');check((await page.locator('#riskHeading').getAttribute('title')).includes('not calendar finish dates'),'detailed model tooltip');check(await page.locator('.risk-metrics [title]').count()===12,'all metric cards explained');check(await page.locator('#nav [data-view="riskV7"]').count()===0,'standalone Risk tab removed');
 await fs.mkdir(path.join(root,'validation'),{recursive:true});await page.locator('.risk-report').evaluate(el=>el.scrollIntoView({block:'start'}));check(await page.locator('.risk-report .panel-head').evaluate(el=>{const box=el.getBoundingClientRect();return [...el.children].every(child=>{const c=child.getBoundingClientRect();return c.top>=box.top&&c.bottom<=box.bottom})}),'dashboard header content fits');await page.screenshot({path:path.join(root,'validation/risk-dashboard.png')});
 const presentation=await page.context().newPage();await presentation.setViewportSize({width:1400,height:1100});await presentation.setContent(html);check(await presentation.locator('svg').count()===5,'download preserves all charts and gauges');check(await presentation.locator('.risk-print').isVisible(),'download offers Print / Save as PDF');await presentation.screenshot({path:path.join(root,'validation/risk-download.png'),fullPage:true});await presentation.pdf({path:path.join(root,'validation/risk-assessment.pdf'),preferCSSPageSize:true,printBackground:true});await presentation.emulateMedia({media:'print'});check(await presentation.locator('.risk-print').isHidden(),'print excludes controls');
 await page.locator('#menuBar details').filter({has:page.locator('summary',{hasText:/^View$/})}).locator('summary').click();await page.locator('#menuBar [data-command="groupSort"]').click();await page.locator('#layoutGroup').selectOption('activity_codes');await page.locator('#codeGroupAdd').selectOption('T1');await page.locator('#codeGroupAddBtn').click();await page.locator('#codeGroupAdd').selectOption('T2');await page.locator('#codeGroupAddBtn').click();await page.locator('[data-code-group="1"]').dragTo(page.locator('[data-code-group="0"]'));check((await page.locator('[data-code-group="0"]').innerText()).includes('Trade'),'code groups drag reorder');await page.locator('#saveLayout').click();await page.locator('#openFilteredActivities').click();check((await page.locator('#activityTable').innerText()).includes('Mechanical'),'code grouping applied');
 const tools=page.locator('#menuBar details').filter({has:page.locator('summary',{hasText:/^Tools$/})});check(await tools.locator('[data-view="riskV7"]').count()===0,'risk report moved out of Tools');check(await tools.locator('[data-command="levelResources"]').count()===1,'actual tool retained');
 await page.locator('.activity-inline-edit.duration').first().fill('4');await page.locator('.activity-inline-edit.duration').first().press('Tab');
 const fileMenu=page.locator('#menuBar details').filter({has:page.locator('summary',{hasText:/^File$/})});await fileMenu.locator('summary').click();await page.locator('[data-command="closeAll"]').click();await page.locator('#closeCancel').click();check(await page.locator('#documentSelect option').count()===2,'Close all cancellation preserves schedules');
 await fileMenu.locator('summary').click();await page.locator('[data-command="closeAll"]').click();await page.locator('#closeSave').click();await page.locator('#saveAsCancel').click();check(await page.locator('#documentSelect option').count()===2,'Save As cancellation preserves schedules');
 await fileMenu.locator('summary').click();await page.locator('[data-command="closeAll"]').click();await page.locator('#closeSave').click();await page.locator('#saveAsCalculation').selectOption('current');const saved=page.waitForEvent('download');await page.locator('#saveAsWrite').click();const xer=await saved;check((await fs.readFile(await xer.path(),'utf8')).includes('%T\tPROJWBS'),'external root parent can save XER');await page.waitForFunction(()=>document.querySelector('#documentSelect').options.length===0);check(await page.locator('#documentSelect option').count()===0,'Close all closes both schedules');check(errors.length===0,'no runtime errors: '+errors.join(';'));console.log(`Browser 8.1 PASS: ${checks} checks.`);
}finally{await browser.close();server.close()}
