import test from 'node:test';
import assert from 'node:assert/strict';
import {model} from './helpers/model.mjs';
import {p6Date,parseXER} from '../src/parser.js';
import {serializeXER} from '../src/serializer.js';
import {runQSRA} from '../src/v7-risk-engine.js';
import {updateTask,setProjectDataDate,reassignTasksToWBS} from '../src/editor.js';
import {buildWBSTree} from '../src/semantic.js';
import {buildActivityRowModel} from '../src/activity-layout.js';
import {calculateCPM,fmtP6,buildCalendar,shiftWorkHours} from '../src/cpm.js';
for(const value of ['2026-02-30','2026-13-01','2026-00-01','2026-01-01 25:00','2026-01-01garbage','2026/02/30'])test(`reject impossible date ${value}`,()=>assert.equal(p6Date(value),null));
test('valid leap date and explicit timezone',()=>{assert.equal(p6Date('2024-02-29 12:34').getDate(),29);assert.equal(p6Date('2026-01-05T08:00:00+02:00').toISOString(),'2026-01-05T06:00:00.000Z')});
test('invalid Date formats safely',()=>assert.equal(fmtP6(new Date('invalid')),''));
test('repeated XER sections preserve all fields',()=>{const m=parseXER('%T\tTASK\n%F\ttask_id\ttask_name\n%R\t1\tOne\n%T\tTASK\n%F\ttask_id\ttask_code\n%R\t2\tA2\n%E');assert.equal(parseXER(serializeXER(m)).table('TASK')[0].task_name,'One')});
test('task edits to new fields survive export',()=>{const m=model([{}]);updateTask(m,'1',{expect_end_date:'2026-03-01 17:00'});assert.equal(parseXER(serializeXER(m)).table('TASK')[0].expect_end_date,'2026-03-01 17:00')});
test('data date addition survives export',()=>{const m=model([{}],[],{PROJECT:[{proj_id:'P'}]});setProjectDataDate(m,'P','2026-02-01 08:00');assert.equal(parseXER(serializeXER(m)).table('PROJECT')[0].data_date,'2026-02-01 08:00')});
test('WBS reassignment validates whole batch before mutation',()=>{const m=model([{wbs_id:'W'},{proj_id:'Q',wbs_id:'QW'}],[],{PROJWBS:[{proj_id:'P',wbs_id:'NEW'}]});assert.throws(()=>reassignTasksToWBS(m,['1','2'],'NEW'));assert.equal(m.table('TASK')[0].wbs_id,'W')});
test('cyclic WBS never hides activities',()=>{const m=model([{wbs_id:'a'}],[],{PROJWBS:[{proj_id:'P',wbs_id:'a',parent_wbs_id:'b'},{proj_id:'P',wbs_id:'b',parent_wbs_id:'a'}]});assert.ok(buildWBSTree(m,'P').length);assert.equal(buildActivityRowModel(m,'P',m.table('TASK'),{groupBy:'wbs_id'}).filter(x=>x.kind==='activity').length,1)});
test('zero lag preserves finish boundary',()=>{const cal=buildCalendar(model(),'C');assert.equal(fmtP6(shiftWorkHours(cal,p6Date('2026-01-05 16:00'),0)),'2026-01-05 16:00')});
test('FF zero lag activities finish together',()=>{const m=model([{},{}],[{pred_task_id:'1',task_id:'2',pred_type:'PR_FF'}]);const c=calculateCPM(m,'P');assert.equal(+c.results[0].ef,+c.results[1].ef)});
for(const opts of [{iterations:NaN},{iterations:Infinity},{minFactor:2,maxFactor:1},{distribution:'unknown'},{targetTaskId:'missing'}])test(`QSRA rejects ${JSON.stringify(opts)}`,()=>assert.ok(runQSRA(model([{}]),'P',opts).error));
test('empty QSRA has actionable error',()=>assert.ok(runQSRA(model(),'P').error));
test('completed activities have zero remaining simulation duration',()=>assert.equal(runQSRA(model([{status_code:'TK_Complete',remain_drtn_hr_cnt:'24'}]),'P',{minFactor:1,modeFactor:1,maxFactor:1}).p50,0));
test('numeric zero remaining does not use original duration',()=>assert.equal(runQSRA(model([{remain_drtn_hr_cnt:0}]),'P',{minFactor:1,modeFactor:1,maxFactor:1}).p50,0));
test('zero uncertainty stays constant for normal and PERT',()=>{for(const distribution of ['normal','pert']){const r=runQSRA(model([{remain_drtn_hr_cnt:'24'}]),'P',{distribution,minFactor:1,modeFactor:1,maxFactor:1});assert.equal(r.minDays,1);assert.equal(r.maxDays,1)}});
