import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {parseXER,XERModel} from '../src/parser.js';
import {canonicalSummary,portabilityMatrix} from '../src/canonical-schema.js';
import {defaultLayout,applyLayoutSort} from '../src/layouts.js';
import {applyFilterGroup} from '../src/filters.js';
import {explainActivity,driverText} from '../src/diagnostics.js';
import {traceFloatPaths} from '../src/float-paths.js';
import {validateProgress,parseProgressCSV,applyProgressRows} from '../src/progress.js';
import {evmRows,evmSummary} from '../src/evm.js';
import {productivityRows,productivitySummary} from '../src/productivity.js';
import {createScenario,scenarioTaskDiff,promoteScenario} from '../src/scenarios.js';
import {AuditLog} from '../src/audit-log.js';
import {recurringHolidayDates,validateCalendarShifts,calendarVisual} from '../src/calendar-tools.js';
import {makeProjectPackage} from '../src/workspace.js';
import {serializeProjectPackage,parseProjectPackage} from '../src/project-package.js';
import {buildBimSets,matchBimRule,reconcileModelLinks} from '../src/bim-advanced.js';
import {normalizeModelMetadata,addActivityBimLinks} from '../src/bim-links.js';
import {calculateCPM,applyCPM} from '../src/cpm.js';
const root=path.resolve(new URL('.',import.meta.url).pathname,'..');
const sample=()=>parseXER(fs.readFileSync(path.join(root,'sample/sample-project.xer'),'utf8'));

test('canonical schema reports neutral project-control domains',()=>{const m=sample();const s=canonicalSummary(m);assert.equal(s.schemaVersion,'4.0');assert.ok(s.counts.activities>0);assert.ok(s.total>0);assert.ok(portabilityMatrix(m).some(x=>x.feature==='BIM links'))});
test('layout sorting and nested-style filter group produce deterministic rows',()=>{const rows=[{task_code:'A20',total_float_hr_cnt:'8'},{task_code:'A10',total_float_hr_cnt:'0'}];const f=applyFilterGroup(rows,{mode:'AND',rules:[{field:'total_float_hr_cnt',op:'lte',value:0}]});assert.equal(f.length,1);const l=defaultLayout();assert.equal(applyLayoutSort(rows,l)[0].task_code,'A10')});
test('calculation diagnostics expose visible predecessor candidate',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id,t=m.table('TASK')[1];const d=explainActivity(m,p,t.task_id);assert.ok(d);assert.equal(typeof driverText(d),'string')});
test('multiple float path tracer returns upstream paths without cycles',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id,t=m.table('TASK').at(-1);const x=traceFloatPaths(m,p,t.task_id,{maxPaths:5});assert.ok(Array.isArray(x));assert.ok(x.length>=1)});
test('progress CSV parses, updates activities and validates inconsistent progress',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id,t=m.table('TASK')[0];t.act_start_date='';t.act_end_date='';const rows=parseProgressCSV(`task_code,phys_complete_pct,remain_drtn_hr_cnt\n${t.task_code},50,8`);assert.equal(applyProgressRows(m,rows),1);assert.equal(m.find('TASK','task_id',t.task_id).phys_complete_pct,'50');assert.ok(validateProgress(m,p,'2026-01-01').some(i=>i.type==='Missing Actual Start'))});
test('EVM rolls activity values into summary metrics',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id;const rows=evmRows(m,p,new Date('2026-01-20'));const s=evmSummary(rows);assert.ok(Number.isFinite(s.bac));assert.ok('spi' in s&&'cpi' in s)});
test('productivity summary reconciles resource assignments',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id;const rows=productivityRows(m,p),s=productivitySummary(rows);assert.ok(rows.length>=0);assert.ok(s.actual>=0&&s.remaining>=0)});
test('scenario clone detects and can promote schedule changes',()=>{const m=sample(),sc=createScenario(m,'Recovery');const t=m.table('TASK')[0];t.remain_drtn_hr_cnt=String(Number(t.remain_drtn_hr_cnt||0)+8);assert.ok(scenarioTaskDiff(m,sc).length);promoteScenario(m,sc);assert.equal(scenarioTaskDiff(m,sc).length,0)});
test('audit log captures and exports structured changes',()=>{const a=new AuditLog();a.add('Edit activity',{task:'A100'});const x=JSON.parse(a.export());assert.equal(x.items.length,1);assert.equal(x.items[0].action,'Edit activity')});
test('calendar helpers support recurring holidays and reject overlapping shifts',()=>{assert.match(recurringHolidayDates(2026,7,1,4),/^2026-08-/);assert.equal(validateCalendarShifts([[480,720],[700,900]]).ok,false);assert.equal(validateCalendarShifts([[480,720],[780,1020]]).ok,true);assert.ok(calendarVisual(sample()).length>0)});
test('portable project package preserves canonical tables and settings',()=>{const m=sample();const pkg=makeProjectPackage({model:m,settings:{hoursPerDay:8},layouts:[defaultLayout()]});const text=serializeProjectPackage(pkg);const x=parseProjectPackage(text);assert.equal(x.schema,'unified-schedule-project');assert.ok(x.tables.some(([n])=>n==='TASK'));assert.equal(x.settings.hoursPerDay,8)});
test('BIM sets and rule matching use local metadata properties',()=>{const meta=normalizeModelMetadata({modelKey:'M',objects:[{guid:'1',name:'Tray',level:'L03',category:'Cable'},{guid:'2',name:'Pipe',level:'L02',category:'Pipe'}]});const sets=buildBimSets(meta,'level',['L03']);assert.equal(sets[0].objectIds.length,1);assert.equal(matchBimRule(meta,{conditions:[{property:'category',value:'Cable'}]}).length,1)});
test('BIM model revision reconciliation preserves stable links and flags missing IDs',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id,t=m.table('TASK')[0];addActivityBimLinks(m,p,t.task_id,[{modelKey:'M',objectId:'1'},{modelKey:'M',objectId:'gone'}]);const oldMeta=normalizeModelMetadata({modelKey:'M',objects:[{guid:'1'},{guid:'gone'}]});const newMeta=normalizeModelMetadata({modelKey:'M',objects:[{guid:'1'},{guid:'2'}]});const r=reconcileModelLinks(m,oldMeta,newMeta);assert.equal(r.checked,2);assert.equal(r.exact,1);assert.equal(r.missing,1)});
test('v4 UI exposes layouts diagnostics progress history workspace and project package',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const id of ['layouts','diagnostics','progressEvm','history','workspace'])assert.match(html,new RegExp(`data-view="${id}"`));assert.match(html,/savePackageBtn/);assert.match(html,/openPackageBtn/)});
test('v4 specialist modules remain separated from app and CPM engine',()=>{for(const f of ['canonical-schema.js','layouts.js','filters.js','diagnostics.js','float-paths.js','progress.js','evm.js','productivity.js','scenarios.js','audit-log.js','calendar-tools.js','workspace.js','bim-advanced.js','project-package.js'])assert.ok(fs.existsSync(path.join(root,'src',f)));const cpm=fs.readFileSync(path.join(root,'src/cpm.js'),'utf8');assert.doesNotMatch(cpm,/IndexedDB|BIM Sets|EVM Summary/)});
test('calculation engine still calculates after v4 modular additions',()=>{const m=sample(),p=m.table('PROJECT')[0]?.proj_id;const c=calculateCPM(m,p,{hoursPerDay:8});applyCPM(m,p,c);assert.ok(c.projectFinish instanceof Date);assert.ok(m.table('TASK').some(t=>t.early_end_date))});
