import test from 'node:test';import assert from 'node:assert/strict';
import {model} from './helpers/model.mjs';import {runQSRA} from '../src/v7-risk-engine.js';import {parseRiskRegister,compileRisks} from '../src/risk-register.js';import {prepareSave} from '../src/save-service.js';import {parseXER} from '../src/parser.js';import {validateModelIntegrity} from '../src/integrity.js';import {buildActivityRowModel} from '../src/activity-layout.js';
const options={iterations:1000,seed:7,minFactor:1,modeFactor:1,maxFactor:1};
test('shared risk event occurs once and impacts both linked tasks in the same iteration',()=>{const m=model([{target_drtn_hr_cnt:'24',remain_drtn_hr_cnt:'24'},{target_drtn_hr_cnt:'24',remain_drtn_hr_cnt:'24'}],[{pred_task_id:'1',task_id:'2'}]);const result=runQSRA(m,'P',{...options,riskRegister:[{id:'R1',probability:100,activities:'A1;A2',minimum:24,likely:24,maximum:24}],targetDays:3});assert.equal(result.baselineDays,2);assert.ok(Math.abs(result.meanDays-4)<1e-10);assert.equal(result.p80,4);assert.equal(result.targetConfidence,0);assert.equal(result.riskEvents[0].occurrences,1000);assert.ok(result.stdDevDays<1e-10);});
test('shared probability draws are reproducible and completed work is not delayed',()=>{const m=model([{remain_drtn_hr_cnt:'24'},{status_code:'TK_Complete'}]);const opts={...options,riskRegister:[{id:'R',probability:50,activities:'A1;A2',minimum:24,likely:24,maximum:24}]};const a=runQSRA(m,'P',opts);assert.deepEqual(a,runQSRA(m,'P',opts));assert.ok(a.riskEvents[0].occurrences>400&&a.riskEvents[0].occurrences<600);assert.equal(a.maxDays,2);assert.equal(a.minDays,1);});
test('risk parsing accepts Excel and quoted CSV and rejects unknown activities',()=>{const rows=parseRiskRegister('Risk ID\tDescription\tProbability %\tActivity codes\tMinimum hours\tMost likely hours\tMaximum hours\nR1\tDelivery\t25%\tA1;A2\t8\t24\t80');assert.equal(rows[0].probability,25);assert.equal(rows[0].likely,24);assert.equal(parseRiskRegister('R1,"Delay, shipment",50,A1,0,2,4')[0].description,'Delay, shipment');assert.throws(()=>compileRisks(rows,model([{}]).table('TASK')),/unknown/);assert.throws(()=>compileRisks([{...rows[0],probability:101}],[]),/probability/);});
test('missing external root parent exports cleanly without mutating live model',()=>{const m=model([{wbs_id:'W'}],[],{PROJWBS:[{wbs_id:'W',proj_id:'P',parent_wbs_id:'EPS',proj_node_flag:'Y',wbs_name:'Project'}]});assert.equal(validateModelIntegrity(m).ok,true);const result=prepareSave(m,{format:'xer'}),copy=parseXER(result.text);assert.equal(copy.table('PROJWBS')[0].parent_wbs_id,'');assert.equal(m.table('PROJWBS')[0].parent_wbs_id,'EPS');assert.ok(prepareSave(m,{format:'mspxml',projectId:'P'}).text.includes('<Project'));});
test('unresolved internal WBS and hierarchy cycles still block exports',()=>{const m=model([],[],{PROJWBS:[{wbs_id:'W',proj_id:'P',parent_wbs_id:''},{wbs_id:'C',proj_id:'P',parent_wbs_id:'MISSING'}]});assert.throws(()=>prepareSave(m,{format:'xer'}),/structural errors/);m.table('PROJWBS')[1].parent_wbs_id='C';assert.throws(()=>prepareSave(m,{format:'xer'}),/structural errors/);});
test('multiple activity-code grouping levels retain each activity exactly once',()=>{const m=model([{},{}],[],{ACTVCODE:[{actv_code_id:'1',actv_code_type_id:'A',actv_code_name:'Area 1'},{actv_code_id:'2',actv_code_type_id:'B',actv_code_name:'Electrical'}],TASKACTV:[{task_id:'1',actv_code_id:'1'},{task_id:'2',actv_code_id:'1'},{task_id:'1',actv_code_id:'2'}]});const rows=buildActivityRowModel(m,'P',m.table('TASK'),{groupBy:'activity_codes',codeGroups:['A','B']});assert.equal(rows[0].label,'Area 1');assert.equal(rows.filter(r=>r.kind==='activity').length,2);assert.ok(rows.some(r=>r.label==='Unassigned'));assert.ok(rows.filter(r=>r.kind==='activity').every(r=>r.depth===2));});
