/* Local GLB viewer for the GitHub Pages app.
   Supports glTF 2.0 GLB with embedded BIN buffers, POSITION + indices triangle primitives,
   node hierarchy, metadata mapping, selection/isolation, orbit/pan/zoom and schedule colouring.
   It intentionally avoids cloud APIs and external libraries. */

const GLB_MAGIC=0x46546c67, CHUNK_JSON=0x4e4f534a, CHUNK_BIN=0x004e4942;
const COMPONENT={5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array};
const TYPE_COUNT={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};

function ident(){return [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}
function mul(a,b){const o=new Array(16).fill(0);for(let r=0;r<4;r++)for(let c=0;c<4;c++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
function translate(x,y,z){const m=ident();m[12]=x;m[13]=y;m[14]=z;return m}
function scale(x,y,z){const m=ident();m[0]=x;m[5]=y;m[10]=z;return m}
function quat(x,y,z,w){const m=ident(),x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;m[0]=1-(yy+zz);m[1]=xy+wz;m[2]=xz-wy;m[4]=xy-wz;m[5]=1-(xx+zz);m[6]=yz+wx;m[8]=xz+wy;m[9]=yz-wx;m[10]=1-(xx+yy);return m}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return [f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]}
function lookAt(eye,target,up=[0,0,1]){const z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x);return [x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]}
function sub(a,b){return [a[0]-b[0],a[1]-b[1],a[2]-b[2]]} function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]} function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]} function norm(a){const l=Math.hypot(...a)||1;return a.map(v=>v/l)}
function orbit(cam){const c=cam.center,r=cam.radius,cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch),cy=Math.cos(cam.yaw),sy=Math.sin(cam.yaw);return [c[0]+r*cp*cy,c[1]+r*cp*sy,c[2]+r*sp]}
function hexToRgb(h){const s=h.replace('#','');return [parseInt(s.slice(0,2),16)/255,parseInt(s.slice(2,4),16)/255,parseInt(s.slice(4,6),16)/255,1]}

export async function parseGLB(file){const ab=await file.arrayBuffer(),dv=new DataView(ab);if(dv.getUint32(0,true)!==GLB_MAGIC)throw new Error('Not a valid GLB file.');const len=dv.getUint32(8,true);if(len!==ab.byteLength)throw new Error('GLB length mismatch.');let off=12,json=null,bin=null;while(off<len){const l=dv.getUint32(off,true),t=dv.getUint32(off+4,true);off+=8;const slice=ab.slice(off,off+l);if(t===CHUNK_JSON)json=JSON.parse(new TextDecoder().decode(slice).replace(/\0+$/,'').trim());else if(t===CHUNK_BIN)bin=slice;off+=l;}if(!json||!bin)throw new Error('GLB requires JSON and BIN chunks.');if((json.asset?.version||'').split('.')[0]!=='2')throw new Error('Only glTF 2.0 is supported.');return buildScene(json,bin,file.name)}

function accessorArray(gltf,bin,ix){const a=gltf.accessors[ix],bv=gltf.bufferViews[a.bufferView];const C=COMPONENT[a.componentType],count=a.count*TYPE_COUNT[a.type],byteOffset=(bv.byteOffset||0)+(a.byteOffset||0);return new C(bin,byteOffset,count)}
function nodeMatrix(n){if(n.matrix)return n.matrix.slice();let m=translate(...(n.translation||[0,0,0]));if(n.rotation)m=mul(m,quat(...n.rotation));if(n.scale)m=mul(m,scale(...n.scale));return m}
function buildScene(gltf,bin,name){const nodes=gltf.nodes||[],meshes=gltf.meshes||[];const parents=new Array(nodes.length).fill(-1);nodes.forEach((n,i)=>(n.children||[]).forEach(c=>parents[c]=i));const world=new Array(nodes.length);function calc(i){if(world[i])return world[i];const local=nodeMatrix(nodes[i]),p=parents[i];world[i]=p>=0?mul(calc(p),local):local;return world[i]}nodes.forEach((_,i)=>calc(i));const items=[];let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];nodes.forEach((n,ni)=>{if(n.mesh==null)return;const mesh=meshes[n.mesh];for(const prim of mesh.primitives||[]){if(prim.mode!=null&&prim.mode!==4)continue;if(prim.attributes?.POSITION==null)continue;const pos=accessorArray(gltf,bin,prim.attributes.POSITION),idx=prim.indices!=null?accessorArray(gltf,bin,prim.indices):null;const positions=new Float32Array(pos.length);positions.set(pos);let indices;if(idx){indices=idx instanceof Uint32Array?new Uint32Array(idx):new Uint32Array(Array.from(idx));}else{indices=new Uint32Array(positions.length/3);for(let i=0;i<indices.length;i++)indices[i]=i;}for(let i=0;i<positions.length;i+=3){const x=positions[i],y=positions[i+1],z=positions[i+2],m=world[ni];const X=m[0]*x+m[4]*y+m[8]*z+m[12],Y=m[1]*x+m[5]*y+m[9]*z+m[13],Z=m[2]*x+m[6]*y+m[10]*z+m[14];min=[Math.min(min[0],X),Math.min(min[1],Y),Math.min(min[2],Z)];max=[Math.max(max[0],X),Math.max(max[1],Y),Math.max(max[2],Z)];}items.push({nodeIndex:ni,nodeName:n.name||`Node ${ni}`,positions,indices,world:world[ni],material:prim.material??null});}});const center=[(min[0]+max[0])/2,(min[1]+max[1])/2,(min[2]+max[2])/2],diag=Math.hypot(max[0]-min[0],max[1]-min[1],max[2]-min[2])||10;return {name,gltf,items,bounds:{min,max,center,diag},nodePath:buildPaths(nodes,parents)}}
function buildPaths(nodes,parents){const memo=new Map();function p(i){if(memo.has(i))return memo.get(i);const s=parents[i]<0?(nodes[i].name||`Node ${i}`):`${p(parents[i])}/${nodes[i].name||`Node ${i}`}`;memo.set(i,s);return s}return nodes.map((_,i)=>p(i))}

export function mountBimViewer(canvas,scene,metadata,{onPick=()=>{}}={}){const gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});if(!gl)throw new Error('WebGL is required by the BIM viewer.');const vs=`attribute vec3 p;uniform mat4 mvp;void main(){gl_Position=mvp*vec4(p,1.0);}`;const fs=`precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}`;function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}const pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,vs));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(pr));const loc={p:gl.getAttribLocation(pr,'p'),mvp:gl.getUniformLocation(pr,'mvp'),c:gl.getUniformLocation(pr,'c')};const uintExt=gl.getExtension('OES_element_index_uint');const gpu=scene.items.map(it=>{const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,it.positions,gl.STATIC_DRAW);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);const max=Math.max(...it.indices);const use32=max>65535;if(use32&&!uintExt)throw new Error('This model uses 32-bit indices and this browser does not support OES_element_index_uint.');const idx=use32?it.indices:new Uint16Array(it.indices);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,idx,gl.STATIC_DRAW);return {...it,vb,ib,count:idx.length,indexType:use32?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT}});const byNode=new Map();(metadata?.objects||[]).forEach(o=>{if(o.nodeIndex!=null){const a=byNode.get(+o.nodeIndex)||[];a.push(o.objectId||o.guid||o.externalId);byNode.set(+o.nodeIndex,a)}});
 const api={camera:{center:[...scene.bounds.center],radius:scene.bounds.diag*1.25,yaw:-0.7,pitch:0.55},selected:new Set(),visible:null,colors:new Map(),destroy(){gpu.forEach(g=>{gl.deleteBuffer(g.vb);gl.deleteBuffer(g.ib)});gl.deleteProgram(pr)},reset(){this.camera.center=[...scene.bounds.center];this.camera.radius=scene.bounds.diag*1.25;this.camera.yaw=-0.7;this.camera.pitch=0.55;render()},setSelection(ids){this.selected=new Set(ids||[]);render()},setVisible(ids){this.visible=ids?new Set(ids):null;render()},setColors(map){this.colors=new Map(map||[]);render()},fit(){this.reset()},pickAt(x,y){const hit=rayPick(scene,this.camera,canvas,x,y,byNode);if(hit){this.selected=new Set(hit.objectIds);onPick(hit);render()}return hit}};
 function render(){const dpr=devicePixelRatio||1,w=Math.max(1,canvas.clientWidth*dpr),h=Math.max(1,canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}gl.enable(gl.DEPTH_TEST);gl.clearColor(0.05,0.07,0.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const eye=orbit(api.camera),view=lookAt(eye,api.camera.center),proj=perspective(55*Math.PI/180,w/h,0.01,scene.bounds.diag*10),vp=mul(proj,view);gl.useProgram(pr);gpu.forEach(g=>{const ids=byNode.get(g.nodeIndex)||[];if(api.visible&&ids.length&&!ids.some(id=>api.visible.has(id)))return;let col=[0.72,0.76,0.82,1];for(const id of ids){if(api.colors.has(id)){col=api.colors.get(id);break}}if(ids.some(id=>api.selected.has(id)))col=[1,0.55,0.1,1];const mvp=mul(vp,g.world);gl.uniformMatrix4fv(loc.mvp,false,new Float32Array(mvp));gl.uniform4fv(loc.c,new Float32Array(col));gl.bindBuffer(gl.ARRAY_BUFFER,g.vb);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,g.ib);gl.drawElements(gl.TRIANGLES,g.count,g.indexType,0)});}
 let drag=null;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,button:e.button,cam:JSON.parse(JSON.stringify(api.camera)),moved:false}});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>3)drag.moved=true;if(drag.button===0){api.camera.yaw=drag.cam.yaw+dx*0.01;api.camera.pitch=Math.max(-1.45,Math.min(1.45,drag.cam.pitch-dy*0.01));}else{const k=api.camera.radius*0.001;api.camera.center=[drag.cam.center[0]-dx*k,drag.cam.center[1]+dy*k,drag.cam.center[2]]}render()});canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved&&drag.button===0)api.pickAt(e.offsetX,e.offsetY);drag=null});canvas.addEventListener('wheel',e=>{e.preventDefault();api.camera.radius*=Math.exp(e.deltaY*0.001);api.camera.radius=Math.max(scene.bounds.diag*0.02,Math.min(scene.bounds.diag*20,api.camera.radius));render()},{passive:false});render();return api}

function rayPick(scene,cam,canvas,x,y,byNode){/* Fast bounding-sphere node pick; stable enough for selection and avoids per-triangle CPU cost. */const dpr=devicePixelRatio||1,w=canvas.clientWidth*dpr,h=canvas.clientHeight*dpr,nx=(x*dpr/w)*2-1,ny=1-(y*dpr/h)*2;const eye=orbit(cam),f=norm(sub(cam.center,eye)),right=norm(cross(f,[0,0,1])),up=cross(right,f),tan=Math.tan(55*Math.PI/360),aspect=w/h,dir=norm([f[0]+right[0]*nx*tan*aspect+up[0]*ny*tan,f[1]+right[1]*nx*tan*aspect+up[1]*ny*tan,f[2]+right[2]*nx*tan*aspect+up[2]*ny*tan]);let best=null;for(const it of scene.items){const ids=byNode.get(it.nodeIndex)||[];if(!ids.length)continue;const c=[it.world[12],it.world[13],it.world[14]],oc=sub(c,eye),t=dot(oc,dir);if(t<=0)continue;const p=[eye[0]+dir[0]*t,eye[1]+dir[1]*t,eye[2]+dir[2]*t],d=Math.hypot(c[0]-p[0],c[1]-p[1],c[2]-p[2]);const r=scene.bounds.diag*0.02;if(d<=r&&(!best||t<best.t))best={t,nodeIndex:it.nodeIndex,objectIds:ids,nodeName:it.nodeName};}return best}

export function taskBimColor(task,date){const d=new Date(date),s=new Date(task.target_start_date||task.early_start_date||task.act_start_date),f=new Date(task.target_end_date||task.early_end_date||task.act_end_date);if(isNaN(s)||isNaN(f))return [0.55,0.58,0.62,1];if(String(task.status_code||'')==='TK_Complete'||f<=d)return [0.18,0.75,0.36,1];if(s<=d&&f>d)return [0.96,0.62,0.12,1];if(s>d)return [0.55,0.58,0.62,0.28];return [0.8,0.2,0.2,1]}
export function colorHexToVec4(h){return hexToRgb(h)}
