import { ensureTable, touch } from './editor.js';

function nextId(rows,field,start=1){let max=start-1;for(const r of rows){const n=Number(r[field]);if(Number.isFinite(n))max=Math.max(max,n)}return String(max+1)}
export function addActivityCodeType(model,{name='New Code Type',scope='AS_Global',seq=1}={}){const t=ensureTable(model,'ACTVTYPE',['actv_code_type_id','actv_code_type','actv_code_type_scope','seq_num']);const id=nextId(t.rows,'actv_code_type_id');const row={actv_code_type_id:id,actv_code_type:name,actv_code_type_scope:scope,seq_num:String(seq)};t.rows.push(row);touch(model);return row;}
export function updateActivityCodeType(model,id,patch){const r=model.find('ACTVTYPE','actv_code_type_id',String(id));if(!r)throw new Error('Activity code type not found.');Object.assign(r,patch);touch(model);return r;}
export function addActivityCode(model,typeId,{code='NEW',description='New Code',parentCodeId=''}={}){if(!model.find('ACTVTYPE','actv_code_type_id',String(typeId)))throw new Error('Activity code type not found.');const t=ensureTable(model,'ACTVCODE',['actv_code_id','actv_code_type_id','parent_actv_code_id','seq_num','short_name','actv_code_name']);const id=nextId(t.rows,'actv_code_id');const row={actv_code_id:id,actv_code_type_id:String(typeId),parent_actv_code_id:String(parentCodeId||''),seq_num:String(t.rows.filter(r=>String(r.actv_code_type_id)===String(typeId)).length+1),short_name:code,actv_code_name:description};t.rows.push(row);touch(model);return row;}
export function updateActivityCode(model,id,patch){const r=model.find('ACTVCODE','actv_code_id',String(id));if(!r)throw new Error('Activity code not found.');Object.assign(r,patch);touch(model);return r;}
export function assignActivityCode(model,taskId,codeId){if(!model.find('TASK','task_id',String(taskId)))throw new Error('Activity not found.');if(!model.find('ACTVCODE','actv_code_id',String(codeId)))throw new Error('Activity code not found.');const t=ensureTable(model,'TASKACTV',['task_id','actv_code_type_id','actv_code_id']);const c=model.find('ACTVCODE','actv_code_id',String(codeId));if(t.rows.some(r=>String(r.task_id)===String(taskId)&&String(r.actv_code_id)===String(codeId)))return null;const row={task_id:String(taskId),actv_code_type_id:String(c.actv_code_type_id),actv_code_id:String(codeId)};t.rows.push(row);touch(model);return row;}
export function removeActivityCodeAssignment(model,taskId,codeId){const t=model.tables.get('TASKACTV');if(!t)return;t.rows=t.rows.filter(r=>!(String(r.task_id)===String(taskId)&&String(r.actv_code_id)===String(codeId)));touch(model);}
export function addUdfType(model,{label='New UDF',name='',dataType='FT_TEXT',tableName='TASK'}={}){const t=ensureTable(model,'UDFTYPE',['udf_type_id','table_name','udf_type_name','udf_type_label','logical_data_type']);const id=nextId(t.rows,'udf_type_id');const row={udf_type_id:id,table_name:tableName,udf_type_name:name||label.replace(/\s+/g,'_'),udf_type_label:label,logical_data_type:dataType};t.rows.push(row);touch(model);return row;}
export function updateUdfType(model,id,patch){const r=model.find('UDFTYPE','udf_type_id',String(id));if(!r)throw new Error('UDF definition not found.');Object.assign(r,patch);touch(model);return r;}
export function setTaskUdfValue(model,taskId,udfTypeId,value){if(!model.find('TASK','task_id',String(taskId)))throw new Error('Activity not found.');const u=model.find('UDFTYPE','udf_type_id',String(udfTypeId));if(!u||String(u.table_name||'').toUpperCase()!=='TASK')throw new Error('Task UDF definition not found.');const t=ensureTable(model,'UDFVALUE',['udf_type_id','fk_id','udf_text','udf_number','udf_date','udf_code_id']);let r=t.rows.find(x=>String(x.udf_type_id)===String(udfTypeId)&&String(x.fk_id)===String(taskId));if(!r){r={udf_type_id:String(udfTypeId),fk_id:String(taskId),udf_text:'',udf_number:'',udf_date:'',udf_code_id:''};t.rows.push(r)}for(const k of ['udf_text','udf_number','udf_date','udf_code_id'])r[k]='';const typ=String(u.logical_data_type||'FT_TEXT').toUpperCase();if(typ.includes('NUMBER')||typ.includes('DOUBLE')||typ.includes('COST'))r.udf_number=String(value??'');else if(typ.includes('DATE'))r.udf_date=String(value??'');else r.udf_text=String(value??'');touch(model);return r;}
export function removeTaskUdfValue(model,taskId,udfTypeId){const t=model.tables.get('UDFVALUE');if(!t)return;t.rows=t.rows.filter(r=>!(String(r.udf_type_id)===String(udfTypeId)&&String(r.fk_id)===String(taskId)));touch(model);}
