import { num, p6Date } from './parser.js';
import { taskRows, predRows, parseCalendarData, getDataDate } from './semantic.js';
import { normalizeSchedulingOptions } from './scheduling-options.js';

const HOUR=3600000;
const pad=n=>String(n).padStart(2,'0');
export function fmtP6(d){if(!(d instanceof Date)||Number.isNaN(d))return ''; return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`}
function ymd(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseTime(s){const m=String(s||'').trim().match(/^(\d{1,2}):(\d{2})(?:\s*(AM|PM))?$/i); if(!m)return null; let h=+m[1],min=+m[2]; const ap=m[3]?.toUpperCase(); if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;return h*60+min;}

export function buildCalendar(model,id,options={}){
  const opt=normalizeSchedulingOptions(options),r=model.find('CALENDAR','clndr_id',String(id)); const defaultHours=num(r?.day_hr_cnt,8)||8; const parsed=parseCalendarData(r?.clndr_data||''); const dayMap=new Map();
  for(let dow=0;dow<7;dow++)dayMap.set(dow,[]);
  for(const d of parsed.days){const dow=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].indexOf(d.day); const periods=d.periods.map(p=>[parseTime(p.start),parseTime(p.finish)]).filter(x=>x[0]!=null&&x[1]!=null&&x[1]>=x[0]); dayMap.set(dow,periods)}
  if(![...dayMap.values()].some(x=>x.length)){for(let d=1;d<=5;d++)dayMap.set(d,[[8*60,8*60+defaultHours*60]])}
  const exceptionMap=new Map();
  if(opt.calendarExceptionMode!=='overrides')for(const [date,periods] of Object.entries(parsed.exceptionPeriods||{}))exceptionMap.set(date,periods.map(p=>[parseTime(p.start),parseTime(p.finish)]).filter(x=>x[0]!=null&&x[1]!=null));
  if(opt.calendarExceptionMode!=='xer')for(const [date,periods] of Object.entries(opt.exceptionOverrides?.[String(id)]||{}))exceptionMap.set(date,(periods||[]).map(x=>[Number(x[0]),Number(x[1])]));
  return {id:String(id||''),row:r,dayMap,defaultHours,exceptions:parsed.exceptions||[],exceptionMap};
}
function dateAtMinutes(d,min){const x=new Date(d);x.setHours(Math.floor(min/60),min%60,0,0);return x}
function intervalsFor(cal,date){const base=new Date(date);base.setHours(0,0,0,0); const ex=cal.exceptionMap?.get(ymd(base));const periods=ex!==undefined?ex:(cal.dayMap.get(base.getDay())||[]);return periods.map(([a,b])=>[dateAtMinutes(base,a),dateAtMinutes(base,b)]);}
export function nextWork(cal,date,forward=true){let d=new Date(date); for(let guard=0;guard<3700;guard++){const ints=intervalsFor(cal,d);if(forward){for(const [s,e] of ints){if(d<=s)return new Date(s); if(d>s&&d<e)return new Date(d)} d=new Date(d);d.setHours(24,0,0,0);}else {for(let i=ints.length-1;i>=0;i--){const [s,e]=ints[i];if(d>=e)return new Date(e);if(d>s&&d<e)return new Date(d)} const x=new Date(d);x.setHours(0,0,0,0);x.setTime(x.getTime()-1);d=x;}}return new Date(date);}
export function addWorkHours(cal,start,hours){let remaining=Math.max(0,num(hours)); let d=nextWork(cal,start,true); if(remaining===0)return d; for(let guard=0;guard<100000&&remaining>1e-9;guard++){const ints=intervalsFor(cal,d); let moved=false;for(const [s,e] of ints){if(d>=e)continue; const cur=d<s?s:d; const avail=(e-cur)/HOUR; if(remaining<=avail+1e-9)return new Date(cur.getTime()+remaining*HOUR); remaining-=avail; d=new Date(e);moved=true;}if(remaining>1e-9){const x=new Date(d);x.setHours(24,0,0,0);d=nextWork(cal,x,true);moved=true} if(!moved)break;} return d;}
export function subtractWorkHours(cal,finish,hours){const remaining=Math.max(0,num(hours));const d=nextWork(cal,finish,false);if(remaining===0)return d;return _subtract(cal,d,remaining);}
function _subtract(cal,d,remaining){for(let guard=0;guard<100000&&remaining>1e-9;guard++){const ints=intervalsFor(cal,d);let moved=false;for(let i=ints.length-1;i>=0;i--){const [s,e]=ints[i];if(d<=s)continue;const cur=d>e?e:d;const avail=(cur-s)/HOUR;if(remaining<=avail+1e-9)return new Date(cur.getTime()-remaining*HOUR);remaining-=avail;d=new Date(s);moved=true;}if(remaining>1e-9){const x=new Date(d);x.setHours(0,0,0,0);x.setTime(x.getTime()-1);d=nextWork(cal,x,false);moved=true}if(!moved)break;}return d;}
export function shiftWorkHours(cal,date,hours){const h=num(hours);return h<0?subtractWorkHours(cal,date,-h):addWorkHours(cal,date,h)}
export function workHoursBetween(cal,start,finish){if(!start||!finish)return 0;if(finish<start)return -workHoursBetween(cal,finish,start);let d=new Date(start),sum=0;for(let guard=0;guard<3700&&d<finish;guard++){for(const [s,e] of intervalsFor(cal,d)){const a=new Date(Math.max(start.getTime(),s.getTime())),b=new Date(Math.min(finish.getTime(),e.getTime()));if(b>a)sum+=(b-a)/HOUR}const x=new Date(d);x.setHours(24,0,0,0);d=x;}return sum}

function relType(r){return String(r.pred_type||'PR_FS').replace(/^PR_/,'').toUpperCase()}
function isComplete(t){return /COMPLETE/i.test(t.status_code||'')}
function isStarted(t){return isComplete(t)||(/ACTIVE|START/i.test(t.status_code||'')&&!!t.act_start_date)}
function duration(t){if(isComplete(t))return 0; const rem=num(t.remain_drtn_hr_cnt,NaN); return Number.isFinite(rem)?Math.max(0,rem):Math.max(0,num(t.target_drtn_hr_cnt||t.orig_drtn_hr_cnt));}
function expectedFinish(t){return p6Date(t.expect_end_date||t.expected_end_date||t.expected_finish_date||t.expect_finish_date)}
function suspendDate(t){return p6Date(t.suspend_date||t.act_suspend_date)}
function resumeDate(t){return p6Date(t.resume_date||t.restart_date||t.act_resume_date)}

export function detectCycles(model,projId){const tasks=taskRows(model,projId),ids=new Set(tasks.map(t=>t.task_id)),rels=predRows(model,projId).filter(r=>ids.has(r.task_id)&&ids.has(r.pred_task_id));const adj=new Map(tasks.map(t=>[t.task_id,[]]));rels.forEach(r=>adj.get(r.pred_task_id).push(r.task_id));const color=new Map(),cycles=[];for(const t of tasks){const root=t.task_id;if(color.get(root))continue;const stack=[{u:root,i:0}],path=[];const pos=new Map();color.set(root,1);path.push(root);pos.set(root,0);while(stack.length){const frame=stack[stack.length-1],neighbors=adj.get(frame.u)||[];if(frame.i>=neighbors.length){color.set(frame.u,2);stack.pop();pos.delete(frame.u);path.pop();continue}const v=neighbors[frame.i++],c=color.get(v)||0;if(c===0){color.set(v,1);stack.push({u:v,i:0});pos.set(v,path.length);path.push(v)}else if(c===1){const i=pos.get(v);if(i!==undefined)cycles.push([...path.slice(i),v])}}}return cycles;}
function topo(model,projId){const tasks=taskRows(model,projId),ids=new Set(tasks.map(t=>t.task_id)),rels=predRows(model,projId).filter(r=>ids.has(r.task_id)&&ids.has(r.pred_task_id));const indeg=new Map(tasks.map(t=>[t.task_id,0])),adj=new Map(tasks.map(t=>[t.task_id,[]]));rels.forEach(r=>{indeg.set(r.task_id,(indeg.get(r.task_id)||0)+1);adj.get(r.pred_task_id).push(r.task_id)});const q=[...tasks.filter(t=>!indeg.get(t.task_id)).map(t=>t.task_id)],order=[];let qi=0;while(qi<q.length){const u=q[qi++];order.push(u);for(const v of adj.get(u)||[]){indeg.set(v,indeg.get(v)-1);if(!indeg.get(v))q.push(v)}}if(order.length!==tasks.length)throw new Error('Schedule contains a relationship cycle. Remove the cycle before recalculating.');return order;}
function constraintSpecs(t){const out=[];for(const [typeKey,dateKey] of [['cstr_type','cstr_date'],['cstr_type2','cstr_date2']]){const type=String(t[typeKey]||'').toUpperCase(),date=p6Date(t[dateKey]);if(!type||!date)continue;if(/MSO|MANDATORY_START|START_ON$/.test(type))out.push({kind:'exactStart',date});else if(/MEO|MANDATORY_FINISH|FINISH_ON$/.test(type))out.push({kind:'exactFinish',date});else if(/SNET|START_NO_EARLIER|START_ON_OR_AFTER/.test(type))out.push({kind:'lowerStart',date});else if(/SNLT|START_NO_LATER|START_ON_OR_BEFORE/.test(type))out.push({kind:'upperStart',date});else if(/FNET|FINISH_NO_EARLIER|FINISH_ON_OR_AFTER/.test(type))out.push({kind:'lowerFinish',date});else if(/FNLT|FINISH_NO_LATER|FINISH_ON_OR_BEFORE/.test(type))out.push({kind:'upperFinish',date});}return out;}
const maxDate=(a,b)=>!a?b:!b?a:(a>b?a:b), minDate=(a,b)=>!a?b:!b?a:(a<b?a:b);
function lagCalendar(options,pred,succ,calFor,projectDefaultCal){const mode=String(options.relationshipLagCalendar||'predecessor').toLowerCase();if(mode==='successor')return calFor(succ);if(mode==='project'||mode==='projectdefault')return projectDefaultCal;if(mode==='24h'||mode==='24hour')return {id:'24h',dayMap:new Map(Array.from({length:7},(_,d)=>[d,[[0,24*60]]])),defaultHours:24,exceptionMap:new Map()};return calFor(pred);}

function externalEndpoint(model,r,options,dd){if(options.externalRelationshipMode==='ignore'||options.externalRelationshipMode==='warnOnly')return null;const p=model.find('TASK','task_id',r.pred_task_id);if(!p)return null;const s=p6Date(p.act_start_date||p.early_start_date||p.target_start_date)||dd;const f=p6Date(p.act_end_date||p.early_end_date||p.target_end_date)||s;return {relStart:s,relFinish:f,external:true};}
function relationCandidate(type,pred,lag,lagCal,succCal,dur){if(type==='SS')return shiftWorkHours(lagCal,pred.relStart,lag);if(type==='FF')return subtractWorkHours(succCal,shiftWorkHours(lagCal,pred.relFinish,lag),dur);if(type==='SF')return subtractWorkHours(succCal,shiftWorkHours(lagCal,pred.relStart,lag),dur);return shiftWorkHours(lagCal,pred.relFinish,lag);}

function calculateNetwork(model,projId,inputOptions={}){
  const options=normalizeSchedulingOptions(inputOptions),tasks=taskRows(model,projId),byId=new Map(tasks.map(t=>[t.task_id,t])),allRels=predRows(model,projId),order=topo(model,projId),calCache=new Map(),warnings=[];
  const defaultCalId=options.defaultCalendarId||model.find('PROJECT','proj_id',String(projId))?.clndr_id||model.table('CALENDAR')[0]?.clndr_id||'';
  const calFor=t=>{const id=t?.clndr_id||defaultCalId;if(!calCache.has(id))calCache.set(id,buildCalendar(model,id,options));return calCache.get(id)};const projectDefaultCal=buildCalendar(model,defaultCalId,options);
  const dd=p6Date(options.dataDate||getDataDate(model,projId))||new Date(),early=new Map(),incoming=new Map(tasks.map(t=>[t.task_id,[]])),outgoing=new Map(tasks.map(t=>[t.task_id,[]])),externalIncoming=new Map(tasks.map(t=>[t.task_id,[]]));
  const invalidRelationships=[];for(const r of allRels){if(incoming.has(r.task_id)&&outgoing.has(r.pred_task_id)){incoming.get(r.task_id).push(r);outgoing.get(r.pred_task_id).push(r)}else if(incoming.has(r.task_id)&&model.find('TASK','task_id',r.pred_task_id)){externalIncoming.get(r.task_id).push(r)}else invalidRelationships.push(r)}
  const startOverrides=options.levelingStartOverrides||{};
  for(const id of order){const t=byId.get(id),cal=calFor(t);let dur=duration(t);const specs=constraintSpecs(t);let es;if(isComplete(t))es=p6Date(t.act_start_date)||p6Date(t.early_start_date)||nextWork(cal,dd,true);else if(isStarted(t)){let restart=resumeDate(t);const susp=suspendDate(t);if(options.suspendResumeMode!=='ignore'&&susp){if(!restart&&options.suspendResumeMode==='strict')throw new Error(`Activity ${t.task_code||id} is suspended but has no resume date.`);if(restart&&restart>dd)es=nextWork(cal,restart,true);else es=nextWork(cal,dd,true)}else es=nextWork(cal,restart&&restart>dd?restart:dd,true)}else es=nextWork(cal,dd,true);
    const ov=p6Date(startOverrides[id]);if(ov)es=maxDate(es,nextWork(cal,ov,true));
    const bypassIncoming=options.outOfSequenceMode==='progressOverride'&&isStarted(t);
    if(!bypassIncoming){for(const r of incoming.get(id)){const p=byId.get(r.pred_task_id),pe=early.get(p.task_id);if(!pe)continue;const lag=num(r.lag_hr_cnt),type=relType(r),lagCal=lagCalendar(options,p,t,calFor,projectDefaultCal);es=maxDate(es,relationCandidate(type,pe,lag,lagCal,cal,dur));}for(const r of externalIncoming.get(id)){const ep=externalEndpoint(model,r,options,dd);if(!ep){warnings.push(`External relationship ${r.pred_task_id} → ${id} was not used.`);continue}const p=model.find('TASK','task_id',r.pred_task_id),lagCal=lagCalendar(options,p,t,calFor,projectDefaultCal);es=maxDate(es,relationCandidate(relType(r),ep,num(r.lag_hr_cnt),lagCal,cal,dur));}}
    for(const c of specs){if(c.kind==='lowerStart')es=maxDate(es,nextWork(cal,c.date,true));if(c.kind==='lowerFinish')es=maxDate(es,subtractWorkHours(cal,nextWork(cal,c.date,true),dur))}const exactStart=specs.find(c=>c.kind==='exactStart'),exactFinish=specs.find(c=>c.kind==='exactFinish');if(exactStart)es=nextWork(cal,exactStart.date,true);
    let ef;if(isComplete(t))ef=p6Date(t.act_end_date)||p6Date(t.early_end_date)||es;else ef=addWorkHours(cal,es,dur);
    const exp=expectedFinish(t);if(exp&&!isComplete(t)&&options.expectedFinishMode!=='ignore'){if(options.expectedFinishMode==='respect'){ef=nextWork(cal,exp,false);dur=Math.max(0,workHoursBetween(cal,es,ef))}else if(options.expectedFinishMode==='constrain'&&exp>ef)ef=nextWork(cal,exp,false)}if(exactFinish&&!isComplete(t)){ef=nextWork(cal,exactFinish.date,false);es=subtractWorkHours(cal,ef,dur)}
    const relStart=isStarted(t)?(p6Date(t.act_start_date)||es):es;let relFinish=isComplete(t)?(p6Date(t.act_end_date)||ef):ef;if(options.outOfSequenceMode==='actualDates'&&p6Date(t.act_end_date))relFinish=p6Date(t.act_end_date);early.set(id,{es,ef,dur,relStart,relFinish,expectedFinish:exp});
  }
  let projectFinish=dd;for(const e of early.values())if(e.ef>projectFinish)projectFinish=e.ef;if(options.finishBy&&options.floatMode==='finishBy'){const f=p6Date(options.finishBy);if(f)projectFinish=f}
  const late=new Map();for(const id of [...order].reverse()){const t=byId.get(id),cal=calFor(t),dur=early.get(id).dur,specs=constraintSpecs(t);let lf=nextWork(cal,projectFinish,false),outs=outgoing.get(id);if(outs.length){lf=null;for(const r of outs){const s=byId.get(r.task_id),sl=late.get(s.task_id);if(!sl)continue;const lag=num(r.lag_hr_cnt),type=relType(r),lagCal=lagCalendar(options,t,s,calFor,projectDefaultCal);let candLf;if(type==='SS'){const b=shiftWorkHours(lagCal,sl.ls,-lag);candLf=addWorkHours(cal,b,dur)}else if(type==='FF')candLf=shiftWorkHours(lagCal,sl.lf,-lag);else if(type==='SF'){const b=shiftWorkHours(lagCal,sl.lf,-lag);candLf=addWorkHours(cal,b,dur)}else candLf=shiftWorkHours(lagCal,sl.ls,-lag);lf=minDate(lf,candLf)}if(lf===null)lf=nextWork(cal,projectFinish,false)}let ls=subtractWorkHours(cal,lf,dur);for(const c of specs){if(c.kind==='upperFinish'){lf=minDate(lf,nextWork(cal,c.date,false));ls=subtractWorkHours(cal,lf,dur)}if(c.kind==='upperStart'){ls=minDate(ls,nextWork(cal,c.date,false));lf=addWorkHours(cal,ls,dur)}if(c.kind==='exactFinish'){lf=nextWork(cal,c.date,false);ls=subtractWorkHours(cal,lf,dur)}if(c.kind==='exactStart'){ls=nextWork(cal,c.date,true);lf=addWorkHours(cal,ls,dur)}}late.set(id,{ls,lf});}
  const results=[];for(const id of order){const t=byId.get(id),cal=calFor(t),e=early.get(id),l=late.get(id);const tfStart=workHoursBetween(cal,e.es,l.ls),tfFinish=workHoursBetween(cal,e.ef,l.lf);const tf=options.totalFloatBasis==='start'?tfStart:options.totalFloatBasis==='minimum'?Math.min(tfStart,tfFinish):tfFinish;let ff=tf;for(const r of outgoing.get(id)){const s=early.get(r.task_id);if(!s)continue;const lag=num(r.lag_hr_cnt),type=relType(r),lagCal=lagCalendar(options,t,byId.get(r.task_id),calFor,projectDefaultCal);let required;if(type==='SS'){required=shiftWorkHours(lagCal,e.relStart,lag);ff=Math.min(ff,workHoursBetween(cal,required,s.es))}else if(type==='FF'){required=shiftWorkHours(lagCal,e.relFinish,lag);ff=Math.min(ff,workHoursBetween(cal,required,s.ef))}else if(type==='SF'){required=shiftWorkHours(lagCal,e.relStart,lag);ff=Math.min(ff,workHoursBetween(cal,required,s.ef))}else{required=shiftWorkHours(lagCal,e.relFinish,lag);ff=Math.min(ff,workHoursBetween(cal,required,s.es))}}if(!outgoing.get(id).length)ff=tf;results.push({task_id:id,es:e.es,ef:e.ef,ls:l.ls,lf:l.lf,totalFloat:tf,freeFloat:ff,duration:e.dur,expectedFinish:e.expectedFinish});}
  return {dataDate:dd,projectFinish,results,cycles:[],order,invalidRelationships,warnings,options};
}

function curveWeights(model,assignment){const curveId=assignment.rsrc_curve_id||assignment.curve_id;if(!curveId)return null;const rows=model.table('RSRCCURVDATA').filter(r=>String(r.rsrc_curve_id||r.curve_id)===String(curveId));let vals=rows.map(r=>num(r.curve_value||r.value||r.curve_pct||r.pct,NaN)).filter(Number.isFinite);if(!vals.length){const row=model.find('RSRCCURV','rsrc_curve_id',String(curveId))||model.find('RSRCCURV','curve_id',String(curveId));if(row)vals=Object.entries(row).filter(([k])=>/pct|value|curve/i.test(k)).map(([,v])=>num(v,NaN)).filter(Number.isFinite)}if(!vals.length)return null;const avg=vals.reduce((a,b)=>a+b,0)/vals.length||1;return vals.map(v=>v/avg);}
function resourceCapacity(model,rsrcId,options){const ov=num(options.resourceCapacityOverrides?.[String(rsrcId)],NaN);if(Number.isFinite(ov)&&ov>0)return ov;const r=model.find('RSRC','rsrc_id',String(rsrcId));for(const k of ['max_qty_per_hr','max_units_per_time','max_units','peak_units']){const v=num(r?.[k],NaN);if(Number.isFinite(v)&&v>0)return v}const d=num(options.resourceDefaultCapacity,0);return d>0?d:Infinity;}
function assignmentDemand(model,a,dur,options,fraction=.5){const qty=num(a.remain_qty||a.target_qty,0);let demand=dur>0?qty/dur:0;if(options.resourceCurveMode==='useCurves'){const w=curveWeights(model,a);if(w?.length){const i=Math.min(w.length-1,Math.max(0,Math.floor(fraction*w.length)));demand*=w[i]}}return demand;}
export function levelResources(model,projId,baseCalc,inputOptions={}){const options=normalizeSchedulingOptions(inputOptions),tasks=taskRows(model,projId),byId=new Map(tasks.map(t=>[t.task_id,t])),assignments=model.table('TASKRSRC'),byTask=new Map();for(const a of assignments){if(!byId.has(a.task_id)||!a.rsrc_id)continue;if(!byTask.has(a.task_id))byTask.set(a.task_id,[]);byTask.get(a.task_id).push(a)}const usage=new Map(),overrides={},conflicts=[],gran=Math.max(.25,num(options.levelingGranularityHours,1)),ordered=[...baseCalc.results].filter(r=>!isComplete(byId.get(r.task_id))).sort((a,b)=>{const ta=byId.get(a.task_id),tb=byId.get(b.task_id),field=options.resourcePriorityField;const pa=num(ta?.[field],9999),pb=num(tb?.[field],9999);return pa-pb||a.es-b.es});
  const bucket=t=>Math.floor(t.getTime()/(gran*HOUR));for(const r of ordered){const as=byTask.get(r.task_id)||[];if(!as.length)continue;const t=byId.get(r.task_id),cal=buildCalendar(model,t.clndr_id,options);let start=new Date(r.es),attempt=0,found=false;while(attempt++<options.levelingMaxIterations){const finish=addWorkHours(cal,start,r.duration);let ok=true;const buckets=[];for(let x=new Date(start),step=0;x<finish&&step++<100000;x=new Date(x.getTime()+gran*HOUR)){if(!intervalsFor(cal,x).some(([s,e])=>x>=s&&x<e))continue;const frac=Math.min(.999,Math.max(0,(x-start)/(Math.max(HOUR,finish-start))));for(const a of as){const cap=resourceCapacity(model,a.rsrc_id,options);if(!Number.isFinite(cap))continue;const dem=assignmentDemand(model,a,r.duration,options,frac),key=`${a.rsrc_id}|${bucket(x)}`,used=usage.get(key)||0;if(used+dem>cap+1e-9){ok=false;break}buckets.push([key,dem])}if(!ok)break}if(ok){for(const [k,d] of buckets)usage.set(k,(usage.get(k)||0)+d);found=true;break}start=shiftWorkHours(cal,start,gran)}if(found&&start>r.es){overrides[r.task_id]=fmtP6(start);conflicts.push({task_id:r.task_id,originalStart:r.es,leveledStart:start,delayHours:workHoursBetween(cal,r.es,start)})}else if(!found)conflicts.push({task_id:r.task_id,unresolved:true,originalStart:r.es,leveledStart:start,delayHours:null});}return {startOverrides:overrides,conflicts};}

export function calculateCPM(model,projId,inputOptions={}){const options=normalizeSchedulingOptions(inputOptions);let calc=calculateNetwork(model,projId,options);if(options.resourceLevelingEnabled){const leveling=levelResources(model,projId,calc,options);calc=calculateNetwork(model,projId,{...options,levelingStartOverrides:leveling.startOverrides});calc.leveling=leveling;}return calc;}

export function applyCPM(model,projId,calc){const taskTable=model.tables.get('TASK');if(taskTable){for(const f of ['early_start_date','early_end_date','late_start_date','late_end_date','total_float_hr_cnt','free_float_hr_cnt','target_start_date','target_end_date','restart_date','reend_date'])if(!taskTable.fields.includes(f))taskTable.fields.push(f)}for(const r of calc.results){const t=model.find('TASK','task_id',r.task_id);if(!t)continue;if(!isComplete(t)){t.early_start_date=fmtP6(r.es);t.early_end_date=fmtP6(r.ef);t.late_start_date=fmtP6(r.ls);t.late_end_date=fmtP6(r.lf);t.total_float_hr_cnt=String(Math.round(r.totalFloat*1000)/1000);t.free_float_hr_cnt=String(Math.round(r.freeFloat*1000)/1000);if(isStarted(t)){t.restart_date=fmtP6(r.es);t.reend_date=fmtP6(r.ef)}else{if(!t.act_start_date)t.target_start_date=fmtP6(r.es);if(!t.act_end_date)t.target_end_date=fmtP6(r.ef)}}}const p=model.find('PROJECT','proj_id',String(projId));if(p){const pt=model.tables.get('PROJECT');const field=('last_recalc_date'in p)?'last_recalc_date':'data_date';if(pt&&!pt.fields.includes(field))pt.fields.push(field);p[field]=fmtP6(calc.dataDate)}model.indexes=new Map();return calc;}
