const sortCollator=new Intl.Collator(undefined,{numeric:true});
const DEFAULT_COLUMNS=['task_code','task_name','wbs_id','target_drtn_hr_cnt','remain_drtn_hr_cnt','early_start_date','early_end_date','phys_complete_pct','total_float_hr_cnt'];
export function defaultBarSettings(){return {showBaseline:true,showActual:true,showProgress:true,showDataDate:true,labelMode:'none',normalColor:'#2b78a8',criticalColor:'#c63535',baselineColor:'#7f8f99',progressColor:'#5aa874',actualColor:'#333333',barHeight:12}}
export function defaultLayout(){return {id:'default',name:'Classic Schedule Layout',columns:[...DEFAULT_COLUMNS],columnWidths:{},groupBy:'wbs_id',sort:[{field:'task_code',dir:1}],filters:[],rowHeight:'compact',timescale:'week',barStyle:'standard',barSettings:defaultBarSettings()}}
export function normalizeLayout(layout={}){const d=defaultLayout();return {...d,...layout,columns:Array.isArray(layout.columns)&&layout.columns.length?[...layout.columns]:[...d.columns],columnWidths:{...(layout.columnWidths||{})},sort:Array.isArray(layout.sort)&&layout.sort.length?layout.sort:[...d.sort],filters:Array.isArray(layout.filters)?layout.filters:[],barSettings:{...d.barSettings,...(layout.barSettings||{})}}}
export function loadLayouts(key='uss-layouts'){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return x.length?x.map(normalizeLayout):[defaultLayout()]}catch{return [defaultLayout()]}}
export function saveLayouts(layouts,key='uss-layouts'){try{localStorage.setItem(key,JSON.stringify(layouts.map(normalizeLayout)));return true}catch{return false}}
export function upsertLayout(layouts,layout){const normalized=normalizeLayout(layout);const i=layouts.findIndex(x=>x.id===normalized.id);if(i>=0)layouts[i]=structuredClone(normalized);else layouts.push(structuredClone(normalized));return layouts}
export function removeLayout(layouts,id){return layouts.filter(x=>x.id!==id||id==='default')}
export function applyLayoutSort(rows,layout){const rules=layout?.sort||[];const groupBy=layout?.groupBy;return [...rows].sort((a,b)=>{if(groupBy){const g=sortCollator.compare(String(a[groupBy]??''),String(b[groupBy]??''));if(g)return g}for(const r of rules){const av=a[r.field]??'',bv=b[r.field]??'';const c=sortCollator.compare(String(av),String(bv));if(c)return c*(r.dir||1)}return 0})}
export function exportLayout(layout){return JSON.stringify(normalizeLayout(layout),null,2)}
export function importLayout(text){const x=normalizeLayout(JSON.parse(String(text||'')));if(!x.id)x.id=`layout-${Date.now()}`;return x}
