import { stableTableEntries } from './determinism.js';
/** Serialize the current in-memory tables back to a Primavera-style XER file. */
export function serializeXER(model){
  const header = model.header?.length ? `ERMHDR\t${model.header.join('\t')}` : 'ERMHDR\t22.12\tGenerated by P6 XER Editor';
  const lines=[header];
  for(const [name,t] of stableTableEntries(model)){
    lines.push(`%T\t${name}`); lines.push(`%F\t${t.fields.join('\t')}`);
    for(const r of t.rows){const vals=t.fields.map(f=>clean(r[f])); if(Array.isArray(r.__extra))vals.push(...r.__extra.map(clean)); lines.push(`%R\t${vals.join('\t')}`)}
  }
  lines.push('%E'); return lines.join('\r\n')+'\r\n';
}
function clean(v){return String(v??'').replace(/[\r\n\t]/g,' ')}
